const Map<String, String> learnQuranBnContentMap = <String, String>{
  'Apply basic madd timing consistently so long vowels remain controlled and accurate.': 'দীর্ঘ স্বরধ্বনি নিয়ন্ত্রিত ও শুদ্ধ রাখতে মৌলিক মাদ্দের সময়মাত্রা ধারাবাহিকভাবে প্রয়োগ করুন।',
  'Apply clear pronunciation (izhar) and merging (idgham) in correct letter contexts.': 'সঠিক হরফের প্রেক্ষিতে পরিষ্কার উচ্চারণ (ইযহার) ও মিশ্র উচ্চারণ (ইদগাম) প্রয়োগ করুন।',
  'Apply madd, waqf, and clear ending control within Al-Fatihah recitation.': 'আল-ফাতিহা তিলাওয়াতে মাদ্দ, ওয়াক্‌ফ এবং শব্দশেষের স্পষ্ট নিয়ন্ত্রণ প্রয়োগ করুন।',
  'Articulate letters from tongue tip, blade, middle, and back with precision.': 'জিহ্বার আগা, ধার, মধ্যভাগ ও পশ্চাৎভাগ থেকে হরফগুলো নিখুঁতভাবে উচ্চারণ করুন।',
  'Assess your own recitation using audio comparison and focused notes.': 'অডিও তুলনা ও লক্ষ্যভিত্তিক নোটের মাধ্যমে নিজের তিলাওয়াত মূল্যায়ন করুন।',
  'Avoid common beginner confusion by mastering high-risk look-alike sets.': 'ঝুঁকিপূর্ণ সাদৃশ্যপূর্ণ হরফ-সেট আয়ত্ত করে নবীনদের সাধারণ বিভ্রান্তি এড়ান।',
  'Break short Quran phrases into word-by-word translation blocks.': 'ছোট কুরআনি ফ্রেজগুলোকে শব্দে-শব্দে অনুবাদের ব্লকে ভাগ করুন।',
  'Combine listening, shadowing, correction, and solo recitation in one final session.': 'একটি চূড়ান্ত সেশনে শোনা, শ্যাডো করা, সংশোধন এবং একক তিলাওয়াত একত্র করুন।',
  'Combine memorization, tajweed, and fluency into prayer-ready short surah recitation.': 'মুখস্থ, তাজবিদ ও সাবলীলতা একত্র করে সালাত-উপযোগী ছোট সূরা তিলাওয়াত গড়ে তুলুন।',
  'Combine noon/tanween, meem saakin, qalqalah, madd, and waqf in one structured recitation round.': 'একটি কাঠামোবদ্ধ তিলাওয়াত রাউন্ডে নূন/তানউইন, মীম সাকিন, কালকালাহ, মাদ্দ ও ওয়াক্‌ফ একত্রে প্রয়োগ করুন।',
  'Combine vocabulary recall, root detection, and ayah mapping in one final round.': 'একটি চূড়ান্ত রাউন্ডে শব্দভান্ডার স্মরণ, মূলধাতু শনাক্তকরণ ও আয়াত ম্যাপিং একত্র করুন।',
  'Connect vocabulary, connectors, and roots in complete ayah understanding.': 'পূর্ণ আয়াত বোঝাপড়ায় শব্দভান্ডার, সংযোজক শব্দ ও মূলধাতুর সংযোগ স্থাপন করুন।',
  'Consolidate clarity, pacing, and stop/restart control in a guided final review.': 'নির্দেশিত চূড়ান্ত রিভিউতে স্বচ্ছতা, গতি ও থামা/পুনরারম্ভের নিয়ন্ত্রণ সুদৃঢ় করুন।',
  'Consolidate recognition, pronunciation, and reading readiness in one guided review.': 'একটি নির্দেশিত রিভিউতে হরফ-চেনা, উচ্চারণ ও পাঠ-প্রস্তুতি সুদৃঢ় করুন।',
  'Consolidate zone awareness, pair correction, and phrase accuracy in one final routine.': 'একটি চূড়ান্ত রুটিনে উচ্চারণস্থান-সচেতনতা, জোড়া সংশোধন ও ফ্রেজের শুদ্ধতা সুদৃঢ় করুন।',
  'Deliver concise declaration ayahs with strong clarity and clean endings.': 'সংক্ষিপ্ত ঘোষণামূলক আয়াতগুলো দৃঢ় স্বচ্ছতা ও পরিষ্কার সমাপ্তিসহ তিলাওয়াত করুন।',
  'Deliver qalqalah letters with clear bounce at stop and continuation positions without exaggeration.': 'থামা ও চলমান অবস্থানে অতিরঞ্জন ছাড়া কালকালাহ হরফগুলো স্পষ্ট প্রতিধ্বনি দিয়ে পড়ুন।',
  'Differentiate hidden and converted sounds while preserving ghunnah control.': 'গুন্নাহ নিয়ন্ত্রণ বজায় রেখে গোপন ও রূপান্তরিত ধ্বনির পার্থক্য করুন।',
  'Differentiate ikhfa shafawi, idgham shafawi, and izhar shafawi inside connected recitation.': 'সংযুক্ত তিলাওয়াতের ভেতরে ইখফা শাফাভি, ইদগাম শাফাভি ও ইযহার শাফাভির পার্থক্য করুন।',
  'Differentiate thick (tafkheem) and thin (tarqeeq) sounds in beginner-friendly contrasts.': 'নবীনদের উপযোগী তুলনায় ভারী (তাফখিম) ও পাতলা (তারকীক) ধ্বনির পার্থক্য করুন।',
  'Differentiate غ and خ from lighter nearby sounds.': 'غ ও خ-কে আশপাশের হালকা ধ্বনি থেকে আলাদা করুন।',
  'Distinguish letters that share a skeleton but differ by dot count and dot position.': 'একই মূল আকৃতি হলেও বিন্দুর সংখ্যা ও অবস্থানভেদে হরফগুলো আলাদা করে চিনুন।',
  'End sounds clearly at sukoon and avoid adding extra vowel echoes after stops.': 'সুকুনে ধ্বনি স্পষ্টভাবে শেষ করুন এবং থামার পরে অতিরিক্ত স্বর-প্রতিধ্বনি যোগ করা এড়ান।',
  'Extract key message points from short passages using learned vocabulary.': 'শেখা শব্দভান্ডার ব্যবহার করে ছোট অংশ থেকে মূল বার্তাগুলো বের করুন।',
  'Fix common articulation confusion in similar or neighboring letters.': 'সাদৃশ্যপূর্ণ বা কাছাকাছি হরফে সাধারণ উচ্চারণগত বিভ্রান্তি সংশোধন করুন।',
  'Hold natural madd for two counts consistently.': 'প্রাকৃতিক মাদ্দ ধারাবাহিকভাবে দুই মাত্রা ধরে রাখুন।',
  'Identify all 29 letters by name and symbol in isolated form.': 'পৃথক রূপে ২৯টি হরফের নাম ও চিহ্ন শনাক্ত করুন।',
  'Identify and correct at least two recurring pronunciation mistakes.': 'অন্তত দুটি পুনরাবৃত্ত উচ্চারণ-ভুল শনাক্ত করে সংশোধন করুন।',
  'Identify shared roots and infer general meaning from related word forms.': 'একই মূলধাতু শনাক্ত করে সংশ্লিষ্ট শব্দরূপ থেকে সাধারণ অর্থ অনুমান করুন।',
  'Improve command-response recitation clarity in a compact three-ayah surah.': 'সংক্ষিপ্ত তিন-আয়াতের সূরায় আহ্বান-প্রতিক্রিয়া ধাঁচের তিলাওয়াতের স্বচ্ছতা উন্নত করুন।',
  'Maintain smooth rhythm and controlled transitions in repeated protection phrases.': 'পুনরাবৃত্ত সুরক্ষা-ফ্রেজে মসৃণ ছন্দ ও নিয়ন্ত্রিত রূপান্তর বজায় রাখুন।',
  'Memorize core Quran words that appear repeatedly across short surahs.': 'ছোট সূরাগুলোতে বারবার আসা মূল কুরআনি শব্দগুলো মুখস্থ করুন।',
  'Move from guided imitation to independent recitation without losing quality.': 'মান নষ্ট না করে নির্দেশিত অনুকরণ থেকে স্বতন্ত্র তিলাওয়াতে এগিয়ে যান।',
  'Pause and restart at safe points without changing meaning or breaking tajweed quality.': 'অর্থ না বদলে এবং তাজবিদের মান নষ্ট না করে নিরাপদ স্থানে থামুন ও পুনরারম্ভ করুন।',
  'Pause at safe points and restart cleanly without distorting word meaning.': 'নিরাপদ স্থানে থেমে শব্দের অর্থ বিকৃত না করে পরিষ্কারভাবে পুনরারম্ভ করুন।',
  'Prevent pronunciation mixing by drilling common confusing pairs in sequence.': 'ক্রম অনুযায়ী সাধারণ বিভ্রান্তিকর জোড়া ড্রিল করে উচ্চারণের মিশ্রণ রোধ করুন।',
  'Produce letters from throat, tongue, and lips using beginner-safe articulation cues.': 'নবীনদের উপযোগী উচ্চারণ নির্দেশনা মেনে গলা, জিহ্বা ও ঠোঁট থেকে হরফ উচ্চারণ করুন।',
  'Produce ء ه ع ح with correct throat depth and controlled breath.': 'ء ه ع ح সঠিক গলার গভীরতা ও নিয়ন্ত্রিত শ্বাসসহ উচ্চারণ করুন।',
  'Read fatha, kasra, and damma with clear vowel quality.': 'ফাতহা, কাসরা ও দাম্মা পরিষ্কার স্বরমানসহ পড়ুন।',
  'Read silent endings and closed syllables without adding extra vowels.': 'অতিরিক্ত স্বর যোগ না করে নীরব শেষ ধ্বনি ও বন্ধ সিলেবল পড়ুন।',
  'Recite Al-Fatihah with stable pace and confident phrase transitions.': 'স্থির গতি ও আত্মবিশ্বাসী ফ্রেজ-রূপান্তরসহ আল-ফাতিহা তিলাওয়াত করুন।',
  'Recite quietly under audio guidance while preserving pronunciation accuracy.': 'উচ্চারণের শুদ্ধতা বজায় রেখে অডিও নির্দেশনায় নরম স্বরে তিলাওয়াত করুন।',
  'Recite short surahs while mentally tracking phrase meaning in sequence.': 'ছোট সূরা তিলাওয়াতের সময় মনে মনে ফ্রেজের অর্থ ধারাবাহিকভাবে অনুসরণ করুন।',
  'Recite warning-and-exception structure with clear emphasis and understanding.': 'সতর্কতা-ও-ব্যতিক্রম কাঠামো স্পষ্ট জোর ও বোঝাপড়াসহ তিলাওয়াত করুন।',
  'Recite with a steady tempo using short breath groups instead of rushed delivery.': 'তাড়াহুড়ো না করে ছোট ছোট শ্বাস-দলে স্থির তালে তিলাওয়াত করুন।',
  'Recognize linking words such as وَ, فَ, and إِنَّ to follow sentence flow.': 'বাক্যের প্রবাহ অনুসরণে وَ, فَ এবং إِنَّ-এর মতো সংযোজক শব্দ চিনুন।',
  'Recognize stable isolated shapes and memorize visual anchors for each letter.': 'স্থির পৃথক আকৃতি চিনুন এবং প্রতিটি হরফের দৃশ্যমান চিহ্ন মনে রাখুন।',
  'Stabilize lips, tongue, and jaw positions for clear consonants before speed practice.': 'গতি অনুশীলনের আগে স্পষ্ট ব্যঞ্জনধ্বনির জন্য ঠোঁট, জিহ্বা ও চোয়ালের অবস্থান স্থিতিশীল করুন।',
  'Strengthen consonant precision and breathing consistency across repeated structures.': 'পুনরাবৃত্ত গঠনে ব্যঞ্জনধ্বনির নিখুঁততা ও শ্বাসের ধারাবাহিকতা শক্তিশালী করুন।',
  'Train your ear to detect rhythm, articulation, and stop points before speaking.': 'উচ্চারণের আগে ছন্দ, উচ্চারণস্থান ও থামার বিন্দু ধরতে আপনার কানকে প্রশিক্ষণ দিন।',
  'Transfer makharij control from drills into connected Quran phrase reading.': 'ড্রিলের মাখারিজ নিয়ন্ত্রণকে সংযুক্ত কুরআনি ফ্রেজ-পাঠে স্থানান্তর করুন।',
  'Understand the major articulation zones and how each zone shapes sound quality.': 'প্রধান উচ্চারণস্থানগুলো এবং প্রতিটি স্থান কীভাবে ধ্বনির গুণমান গঠন করে তা বুঝুন।',
  'Understand why tajweed matters and identify major rule families before drilling.': 'ড্রিল শুরুর আগে তাজবিদ কেন গুরুত্বপূর্ণ তা বুঝুন এবং প্রধান নিয়ম-পরিবারগুলো শনাক্ত করুন।',
  'Use lips and ghunnah correctly for ف ب م و and nasal continuity.': 'ف ب م و-এর জন্য ঠোঁট ও গুন্নাহ সঠিকভাবে ব্যবহার করুন এবং নাসিক্য ধ্বনির ধারাবাহিকতা বজায় রাখুন।',
  'Use listen-repeat-correct cycles to fix articulation and tajweed drift quickly.': 'উচ্চারণ ও তাজবিদে বিচ্যুতি দ্রুত ঠিক করতে শুনুন-পুনরাবৃত্তি-সংশোধন চক্র ব্যবহার করুন।',
  'Use planned breathing so recitation stays calm and consistent from start to end.': 'পরিকল্পিত শ্বাস ব্যবহার করুন, যাতে শুরু থেকে শেষ পর্যন্ত তিলাওয়াত শান্ত ও ধারাবাহিক থাকে।',
  'Alternate pairs slowly: ء/ه and ع/ح while preserving each letter identity.': 'প্রতিটি হরফের স্বতন্ত্রতা বজায় রেখে ধীরে ধীরে জোড়াগুলো বদলে পড়ুন: ء/ه এবং ع/ح।',
  'Annotate one short surah with rule labels, then recite it slowly with full rule awareness.': 'একটি ছোট সূরায় নিয়মের লেবেল দিন, তারপর পূর্ণ নিয়ম-সচেতনতায় ধীরে তিলাওয়াত করুন।',
  'Classify examples into izhar or idgham and recite each with deliberate pacing.': 'উদাহরণগুলোকে ইযহার বা ইদগাম হিসেবে শ্রেণিবদ্ধ করুন এবং প্রতিটি সচেতন গতি রেখে তিলাওয়াত করুন।',
  'Compare qaaf/kaaf, saad/seen, and taa/taa-heavy slowly while keeping mouth posture stable.': 'মুখের ভঙ্গি স্থির রেখে ধীরে ধীরে ق/ك, ص/س এবং ت/ط তুলনা করুন।',
  'Complete a final review cycle: word test, root test, phrase mapping, then one meaning-led recitation.': 'চূড়ান্ত রিভিউ চক্র সম্পন্ন করুন: শব্দ পরীক্ষা, মূলধাতু পরীক্ষা, ফ্রেজ ম্যাপিং, তারপর অর্থ-নির্দেশিত একবার তিলাওয়াত।',
  'Complete the final review: identify random letters, compare look-alikes, then read beginner examples with harakat.': 'চূড়ান্ত রিভিউ সম্পন্ন করুন: এলোমেলো হরফ শনাক্ত করুন, সাদৃশ্যপূর্ণগুলো তুলনা করুন, তারপর হারাকাতসহ নবীন উদাহরণ পড়ুন।',
  'Complete the review block: pair contrast, madd count, pause-restart, then one self-recorded recitation.': 'রিভিউ ব্লক সম্পন্ন করুন: জোড়া তুলনা, মাদ্দ গণনা, থামা-পুনরারম্ভ, তারপর একটি স্ব-রেকর্ড করা তিলাওয়াত।',
  'Complete the review cycle: map, zone drill, pair correction, then one recorded phrase recitation.': 'রিভিউ চক্র সম্পন্ন করুন: ম্যাপ, জোন ড্রিল, জোড়া সংশোধন, তারপর একটি রেকর্ড করা ফ্রেজ তিলাওয়াত।',
  'Complete three correction loops and track improvement after each loop.': 'তিনটি সংশোধন লুপ সম্পন্ন করুন এবং প্রতিটি লুপের পর উন্নতি নথিভুক্ত করুন।',
  'Complete two shadow rounds and keep madd/stop timing aligned to audio.': 'দুটি শ্যাডো রাউন্ড সম্পন্ন করুন এবং মাদ্দ/থামার সময়মাত্রা অডিওর সাথে মিলিয়ে রাখুন।',
  'Cycle through consonant-vowel sets such as بَ بِ بُ and نَ نِ نُ while keeping a steady pace.': 'স্থির গতি রেখে بَ بِ بُ এবং نَ نِ نُ-এর মতো ব্যঞ্জন-স্বর সেট ঘুরিয়ে অনুশীলন করুন।',
  'Drill ق/ك, ج/ش, and ت/د/ط sets while maintaining placement discipline.': 'উচ্চারণস্থান শৃঙ্খলা বজায় রেখে ق/ك, ج/ش এবং ت/د/ط সেট ড্রিল করুন।',
  'Group words by root (for example ر-ح-م, غ-ف-ر, ه-د-ي) and summarize each root theme.': 'শব্দগুলোকে মূলধাতু অনুযায়ী গুচ্ছ করুন (যেমন ر-ح-م, غ-ف-ر, ه-د-ي) এবং প্রতিটি মূলের থিম সংক্ষেপে লিখুন।',
  'Highlight connectors in short phrases and explain their role in meaning sequence.': 'ছোট ফ্রেজে সংযোজক শব্দ চিহ্নিত করুন এবং অর্থের ধারাবাহিকতায় তাদের ভূমিকা ব্যাখ্যা করুন।',
  'Listen to one short recitation and mark where rules like ikhfa, qalqalah, and madd occur.': 'একটি ছোট তিলাওয়াত শুনে ইখফা, কালকালাহ ও মাদ্দের মতো নিয়ম কোথায় এসেছে তা চিহ্নিত করুন।',
  'Map each word in two phrases, then restate complete meaning in one sentence.': 'দুটি ফ্রেজের প্রতিটি শব্দ ম্যাপ করুন, তারপর এক বাক্যে পূর্ণ অর্থ পুনর্ব্যক্ত করুন।',
  'Mark breath points on one short passage and recite with stable tempo.': 'একটি ছোট অংশে শ্বাসের পয়েন্ট চিহ্নিত করুন এবং স্থির তালে তিলাওয়াত করুন।',
  'Mark safe stops and recite with deliberate pause-restart discipline.': 'নিরাপদ থামার স্থান চিহ্নিত করুন এবং সচেতন থামা-পুনরারম্ভ শৃঙ্খলায় তিলাওয়াত করুন।',
  'Pause mentally at إِلَّا and continue with controlled contrast pacing.': 'إِلَّا-এ মানসিকভাবে বিরতি নিয়ে নিয়ন্ত্রিত বৈপরীত্য-গতিতে এগিয়ে যান।',
  'Practice closed endings in words like قل, رب, and الفلق with crisp final consonants.': 'قل, رب এবং الفلق-এর মতো শব্দে শেষ ব্যঞ্জন স্পষ্ট রেখে বন্ধ সমাপ্তি অনুশীলন করুন।',
  'Practice each zone slowly with short bursts and watch for common mistakes in airflow and tongue placement.': 'প্রতিটি জোন ছোট ছোট ধাপে ধীরে অনুশীলন করুন এবং বায়ুপ্রবাহ ও জিহ্বার অবস্থানের সাধারণ ভুলগুলো লক্ষ্য করুন।',
  'Practice iqlab before baa and ikhfa before target letters in short phrase sets.': 'ছোট ফ্রেজ-সেটে ب-এর আগে ইকলাব এবং নির্দিষ্ট হরফের আগে ইখফা অনুশীলন করুন।',
  'Practice lip closure/release and ghunnah on noon-meem combinations.': 'নূন-মীম সমন্বয়ে ঠোঁট বন্ধ/ছাড়ার কৌশল ও গুন্নাহ অনুশীলন করুন।',
  'Practice meem endings before baa/meem/other letters with controlled lip closure.': 'নিয়ন্ত্রিত ঠোঁট বন্ধ রেখে ب/م/অন্যান্য হরফের আগে মীম-সমাপ্তি অনুশীলন করুন।',
  'Practice one-ayah passages with planned stops and clean restarts.': 'পরিকল্পিত থামা ও পরিষ্কার পুনরারম্ভসহ এক-আয়াতের অংশ অনুশীলন করুন।',
  'Practice posture cues in short sets: qa, ka, sa, sha, da, dha with intentional precision.': 'ইচ্ছাকৃত নিখুঁততায় ছোট সেটে ভঙ্গি-নির্দেশনা অনুশীলন করুন: qa, ka, sa, sha, da, dha।',
  'Practice recurring مِنْ شَرِّ segments with steady pace and articulation.': 'পুনরাবৃত্ত مِنْ شَرِّ অংশগুলো স্থির গতি ও শুদ্ধ উচ্চারণে অনুশীলন করুন।',
  'Practice short words like بسم, قل, and رب with calm stops and clean endings.': 'بسم, قل ও رب-এর মতো ছোট শব্দ শান্ত বিরতি ও পরিষ্কার সমাপ্তিসহ অনুশীলন করুন।',
  'Practice the full isolated letter map and describe one shape cue for every row.': 'পূর্ণ পৃথক-হরফ মানচিত্র অনুশীলন করুন এবং প্রতিটি সারির জন্য একটি আকৃতি-সংকেত বর্ণনা করুন।',
  'Practice غ/خ in short words and monitor airflow friction consistency.': 'ছোট শব্দে غ/خ অনুশীলন করুন এবং বায়ুপ্রবাহের ঘর্ষণের ধারাবাহিকতা পর্যবেক্ষণ করুন।',
  'Read each ayah separately, then join all three in one smooth pass.': 'প্রতিটি আয়াত আলাদা পড়ুন, তারপর তিনটিই একবারে মসৃণভাবে যুক্ত করে পড়ুন।',
  'Read one slow round and one salah-tempo round while tracking phrase boundaries.': 'ফ্রেজের সীমারেখা অনুসরণ করে এক রাউন্ড ধীরে এবং এক রাউন্ড সালাতের গতিতে পড়ুন।',
  'Read qalqalah examples at wasl and waqf and compare bounce intensity.': 'ওয়াসল ও ওয়াক্‌ফে কালকালাহর উদাহরণ পড়ুন এবং প্রতিধ্বনির তীব্রতা তুলনা করুন।',
  'Read selected ayahs with one deliberate stop and one correct restart per line.': 'নির্বাচিত আয়াতগুলো পড়ুন; প্রতি লাইনে একটি সচেতন থামা ও একটি সঠিক পুনরারম্ভ রাখুন।',
  'Recite Al-Ikhlas three rounds and correct one issue after each round.': 'আল-ইখলাস তিন রাউন্ড তিলাওয়াত করুন এবং প্রতিটি রাউন্ডের পর একটি করে ভুল সংশোধন করুন।',
  'Recite An-Naas in one breath-managed flow and review weak consonant points.': 'আন-নাস শ্বাস-নিয়ন্ত্রিত এক প্রবাহে তিলাওয়াত করুন এবং দুর্বল ব্যঞ্জন পয়েন্টগুলো পর্যালোচনা করুন।',
  'Recite a 4-surah sequence in one session and self-check accuracy, pace, and stops.': 'এক সেশনে ৪-সূরার ধারাবাহিকতা তিলাওয়াত করুন এবং শুদ্ধতা, গতি ও বিরতি নিজে যাচাই করুন।',
  'Recite one short surah slowly and pause after each ayah to summarize meaning.': 'একটি ছোট সূরা ধীরে তিলাওয়াত করুন এবং প্রতিটি আয়াতের পর থেমে অর্থ সংক্ষেপে বলুন।',
  'Recite selected phrases and annotate one articulation focus in each phrase.': 'নির্বাচিত ফ্রেজ তিলাওয়াত করুন এবং প্রতিটি ফ্রেজে একটি করে উচ্চারণ-ফোকাস চিহ্নিত করুন।',
  'Record one passage, compare against model, and write 3 improvement notes.': 'একটি অংশ রেকর্ড করুন, মডেলের সঙ্গে তুলনা করুন এবং উন্নতির ৩টি নোট লিখুন।',
  'Record, compare with model audio, and apply one fix per detected error.': 'রেকর্ড করুন, মডেল অডিওর সাথে তুলনা করুন, এবং শনাক্ত প্রতিটি ভুলে একটি করে সংশোধন প্রয়োগ করুন।',
  'Review the zone map and point each letter to its origin before reciting it.': 'তিলাওয়াতের আগে জোন ম্যাপ রিভিউ করুন এবং প্রতিটি হরফকে তার উচ্চারণস্থানের সাথে মিলিয়ে নিন।',
  'Run a 3-pass listening cycle and list 3 sound cues from memory.': '৩-ধাপের শ্রবণ চক্র চালান এবং স্মৃতি থেকে ৩টি ধ্বনি-সংকেত লিখুন।',
  'Run a full sequence: listen, shadow, solo, compare, then final confidence pass.': 'পূর্ণ ধারা চালান: শুনুন, শ্যাডো করুন, একক পড়ুন, তুলনা করুন, তারপর আত্মবিশ্বাসের চূড়ান্ত রাউন্ড দিন।',
  'Run correction pairs: ق/ك, س/ص, ت/ط, د/ذ, ح/ه, ع/ء in three rounds.': 'তিন রাউন্ডে সংশোধনী জোড়া চালান: ق/ك, س/ص, ت/ط, د/ذ, ح/ه, ع/ء।',
  'Run pair drills for س/ص, د/ذ, ز/ظ, ق/ك, and ح/ه in three slow rounds.': 'তিনটি ধীর রাউন্ডে س/ص, د/ذ, ز/ظ, ق/ك এবং ح/ه জোড়া ড্রিল করুন।',
  'Run the dot-family drill: baa/taa/thaa, jeem/haa/khaa, and faa/qaaf.': 'বিন্দু-পরিবার ড্রিল করুন: baa/taa/thaa, jeem/haa/khaa এবং faa/qaaf।',
  'Shadow once at medium pace, then do one full solo recitation.': 'মধ্যম গতিতে একবার শ্যাডো করুন, তারপর একবার পূর্ণ একক তিলাওয়াত করুন।',
  'Study 20 common words and identify at least 10 inside guided examples.': '২০টি সাধারণ শব্দ অধ্যয়ন করুন এবং নির্দেশিত উদাহরণে অন্তত ১০টি শনাক্ত করুন।',
  'Take one ayah, label each word role, then explain the ayah meaning aloud.': 'একটি আয়াত নিন, প্রতিটি শব্দের ভূমিকা চিহ্নিত করুন, তারপর আয়াতের অর্থ উচ্চস্বরে ব্যাখ্যা করুন।',
  'Use a 2-2 beat rhythm and inhale only at planned phrase boundaries.': '২-২ বিটের ছন্দ ব্যবহার করুন এবং শুধু পরিকল্পিত ফ্রেজ-সীমায় শ্বাস নিন।',
  'Use beat-count pacing for natural madd and verify consistent length across a short ayah.': 'প্রাকৃতিক মাদ্দের জন্য বিট-গণনা গতি ব্যবহার করুন এবং একটি ছোট আয়াতে দৈর্ঘ্যের ধারাবাহিকতা যাচাই করুন।',
  'Use call-and-response: say each name aloud while pointing to its symbol from right to left.': 'কল-এন্ড-রেসপন্স পদ্ধতি ব্যবহার করুন: ডান থেকে বামে প্রতীকে ইশারা করে প্রতিটি নাম উচ্চস্বরে বলুন।',
  'Use finger counting and beat pacing for aa, ee, and oo sounds in short words.': 'ছোট শব্দে aa, ee ও oo ধ্বনির জন্য আঙুলে গোনা ও বিট-গতি ব্যবহার করুন।',
  'Use the comparison grid and read each pair in contrast: د/ذ, ر/ز, س/ش, ص/ض, ط/ظ, ع/غ.': 'তুলনা গ্রিড ব্যবহার করে প্রতিটি জোড়া বৈপরীত্যে পড়ুন: د/ذ, ر/ز, س/ش, ص/ض, ط/ظ, ع/غ।',
  'Write 3 short reflections from one surah using your word-by-word notes.': 'আপনার শব্দে-শব্দে নোট ব্যবহার করে একটি সূরা থেকে ৩টি সংক্ষিপ্ত প্রতিফলন লিখুন।',
  'Al-Asr meaning-led pacing': 'আল-আসর: অর্থনির্দেশিত গতি নিয়ন্ত্রণ',
  'Al-Falaq protective rhythm training': 'আল-ফালাক: সুরক্ষামূলক ছন্দের অনুশীলন',
  'Al-Fatihah structure and flow': 'আল-ফাতিহা: গঠন ও প্রবাহ',
  'Al-Fatihah tajweed and stop points': 'আল-ফাতিহা: তাজবিদ ও থামার পয়েন্ট',
  'Al-Ikhlas precision practice': 'আল-ইখলাস: নিখুঁততার অনুশীলন',
  'Al-Kawthar fluency and confidence drill': 'আল-কাউসার: সাবলীলতা ও আত্মবিশ্বাস ড্রিল',
  'Aligned shadow and solo transfer': 'সমন্বিত শ্যাডো থেকে একক তিলাওয়াতে স্থানান্তর',
  'Alphabet orientation and letter names': 'বর্ণমালা পরিচিতি ও হরফের নাম',
  'An-Naas articulation and breath control': 'আন-নাস: উচ্চারণ ও শ্বাস নিয়ন্ত্রণ',
  'Applied articulation in short phrases': 'ছোট ফ্রেজে প্রয়োগমূলক উচ্চারণ',
  'Arabic Letters': 'আরবি হরফ',
  'Audio-Assisted Lessons': 'অডিও-সহায়তায় পাঠ',
  'Audio-guided correction loop': 'অডিও-নির্দেশিত সংশোধন চক্র',
  'Ayah-level meaning mapping': 'আয়াত-স্তরের অর্থ মানচিত্র',
  'Breath and pacing control': 'শ্বাস ও গতি নিয়ন্ত্রণ',
  'Confusion-pair correction': 'বিভ্রান্তিকর জোড়া সংশোধন',
  'Connector words and particles': 'সংযোজক শব্দ ও পার্টিকল',
  'Contrast-pair precision drill': 'বৈপরীত্য-জোড়া নিখুঁততা ড্রিল',

  // Arabic letters unit additional coverage.
  'Alphabet map': 'বর্ণমালা মানচিত্র',
  'Shape families': 'আকৃতি পরিবার',
  'Comparison drills': 'তুলনা ড্রিল',
  'Articulation cues': 'উচ্চারণ নির্দেশনা',
  'Harakat practice': 'হারাকাত অনুশীলন',
  'Revision challenge': 'রিভিশন চ্যালেঞ্জ',
  'Complete this sequence in order. Each section prepares the next skill.':
      'এই ক্রমে পুরো ধারাটি সম্পন্ন করুন। প্রতিটি অংশ পরের দক্ষতার জন্য প্রস্তুত করে।',

  'Alif': 'আলিফ',
  'Baa': 'বা',
  'Taa': 'তা',
  'Thaa': 'ছা',
  'Jeem': 'জীম',
  'Haa': 'হা',
  'Khaa': 'খা',
  'Daal': 'দাল',
  'Dhaal': 'যাল',
  'Raa': 'রা',
  'Zay': 'যাই',
  'Seen': 'সীন',
  'Sheen': 'শীন',
  'Saad': 'সাদ',
  'Daad': 'দাদ',
  'Taa (heavy)': 'তা (ভারী)',
  'Zaa': 'যা',
  'Ayn': 'আইন',
  'Ghayn': 'গয়ন',
  'Faa': 'ফা',
  'Qaaf': 'ক্বাফ',
  'Kaaf': 'কাফ',
  'Laam': 'লাম',
  'Meem': 'মীম',
  'Noon': 'নূন',
  'Haa (light)': 'হা (হালকা)',
  'Waaw': 'ওয়াও',
  'Yaa': 'ইয়া',
  'Hamzah': 'হামযাহ',

  'Straight vertical stroke': 'সোজা উল্লম্ব দাগ',
  'One dot below': 'নিচে একটি বিন্দু',
  'Two dots above': 'উপরে দুটি বিন্দু',
  'Three dots above': 'উপরে তিনটি বিন্দু',
  'Body with one dot below': 'মূল আকৃতির নিচে একটি বিন্দু',
  'Same body without dots': 'একই আকৃতি, বিন্দু ছাড়া',
  'Same body with one dot above': 'একই আকৃতি, উপরে একটি বিন্দু',
  'Single right curve': 'ডানদিকে একক বাঁক',
  'Daal shape with one dot above': 'দাল আকৃতি, উপরে একটি বিন্দু',
  'Short descending curve': 'ছোট নেমে যাওয়া বাঁক',
  'Raa shape with one dot above': 'রা আকৃতি, উপরে একটি বিন্দু',
  'Three-tooth shape': 'তিন-দাঁতের আকৃতি',
  'Seen with three dots above': 'সীন আকৃতির উপরে তিনটি বিন্দু',
  'Broad closed curve': 'প্রশস্ত বন্ধ বাঁক',
  'Saad with one dot above': 'সাদ আকৃতি, উপরে একটি বিন্দু',
  'Rounded body with stem': 'দণ্ডসহ গোল আকৃতি',
  'Heavy taa with one dot above': 'ভারী তা আকৃতি, উপরে একটি বিন্দু',
  'Open-loop throat letter': 'খোলা-লুপ গলার হরফ',
  'Ayn with one dot above': 'আইন আকৃতি, উপরে একটি বিন্দু',
  'Loop with one dot above': 'লুপ আকৃতি, উপরে একটি বিন্দু',
  'Loop with two dots above': 'লুপ আকৃতি, উপরে দুটি বিন্দু',
  'Tall stem with angle': 'কোণযুক্ত লম্বা দণ্ড',
  'Long upward stroke': 'উপরে উঠা লম্বা দাগ',
  'Rounded closed bowl': 'গোল বন্ধ বাটি-আকৃতি',
  'Bowl with one dot above': 'বাটি-আকৃতির উপরে একটি বিন্দু',
  'Open breathing circle': 'খোলা শ্বাসধ্বনির বৃত্ত',
  'Small loop and tail': 'ছোট লুপ ও লেজ',
  'Two dots below in isolated form': 'পৃথক রূপে নিচে দুটি বিন্দু',
  'Quick throat stop mark': 'দ্রুত গলা-বন্ধ ধ্বনির চিহ্ন',

  'Skeleton Family: ب ت ث': 'মূল আকৃতি পরিবার: ب ت ث',
  'Skeleton Family: ج ح خ': 'মূল আকৃতি পরিবার: ج ح خ',
  'Curved Pair: د ذ and ر ز': 'বাঁকানো জোড়া: د ذ এবং ر ز',
  'Learn one base shape and read dots correctly.':
      'একটি মূল আকৃতি শিখে বিন্দুগুলো সঠিকভাবে পড়ুন।',
  'Keep shape constant and change only the dot rule.':
      'আকৃতি স্থির রেখে শুধু বিন্দুর নিয়ম বদলান।',
  'No dot is ح, below dot is ج, above dot is خ.':
      'বিন্দু নেই ح, নিচে বিন্দু ج, উপরে বিন্দু خ।',
  'Say the dot count first, then the letter name.':
      'আগে বিন্দুর সংখ্যা বলুন, তারপর হরফের নাম বলুন।',
  'Spot the same body with and without dot.': 'একই আকৃতি বিন্দু ছাড়া ও বিন্দুসহ আলাদা করুন।',
  'If you see one dot above the curve, pick the dotted partner.': 'বাঁকের উপরে একটি বিন্দু দেখলে বিন্দুসহ হরফটি নিন।',
  'Tooth Family: س ش': 'দাঁত-আকৃতি পরিবার: س ش',
  'Read three teeth shape with dot awareness.': 'বিন্দুর সচেতনতা রেখে তিন-দাঁতের আকৃতি পড়ুন।',
  'Three dots above converts س into ش.': 'উপরে তিনটি বিন্দু দিলে س, ش হয়ে যায়।',
  'Heavy Pair Families': 'ভারী জোড়া পরিবার',
  'Separate light and heavy look-alikes.': 'হালকা ও ভারী সাদৃশ্যপূর্ণ হরফ আলাদা করুন।',
  'Heavy letters sound fuller and often have broader shapes.': 'ভারী হরফের ধ্বনি ভরাট এবং আকৃতি প্রায়ই চওড়া হয়।',
  'Throat Pair: ع غ': 'গলার জোড়া: ع غ',
  'Control sound depth while observing one-dot difference.': 'একটি বিন্দুর পার্থক্য দেখে ধ্বনির গভীরতা নিয়ন্ত্রণ করুন।',
  'غ keeps the same body as ع with one dot above.': 'ع-এর একই আকৃতিতে উপরে একটি বিন্দু দিলে غ হয়।',
  'Loop Pair: ف ق': 'লুপ জোড়া: ف ق',
  'Distinguish one dot and two dots quickly.': 'একটি ও দুটি বিন্দুর পার্থক্য দ্রুত চিনুন।',
  'Practice as a pair repeatedly: فَ then قَ.': 'জোড়া হিসেবে বারবার অনুশীলন করুন: فَ তারপর قَ।',

  'د / ذ and ر / ز': 'د / ذ এবং ر / ز',
  'ص / ض and ط / ظ': 'ص / ض এবং ط / ظ',
  'ع / غ and ف / ق': 'ع / غ এবং ف / ق',
  'Same body; 1 dot below, 2 above, 3 above.': 'একই আকৃতি; নিচে ১ বিন্দু, উপরে ২, উপরে ৩।',
  'Reading dot position too quickly and swapping ب with ت.': 'বিন্দুর অবস্থান দ্রুত পড়ে ب এবং ت অদলবদল করা।',
  'Same body; below dot for ج, no dot for ح, above dot for خ.': 'একই আকৃতি; ج-এর নিচে বিন্দু, ح-এ বিন্দু নেই, خ-এর উপরে বিন্দু।',
  'Pronouncing ح like English h; it is deeper and breathier.': 'ح-কে ইংরেজি h-এর মতো বলা; এটি আরও গভীর ও শ্বাসময়।',
  'Each dotted form adds one dot above the same curved shape.': 'একই বাঁকানো আকৃতিতে বিন্দুযুক্ত রূপে উপরে একটি বিন্দু যোগ হয়।',
  'Skipping the subtle sound difference between د and ذ.': 'د এবং ذ-এর সূক্ষ্ম ধ্বনি-পার্থক্য এড়িয়ে যাওয়া।',
  'Three dots above turns seen into sheen.': 'উপরে তিনটি বিন্দু দিলে seen, sheen হয়ে যায়।',
  'Forgetting that ش uses a "sh" sound, not plain s.': 'শ-তে "sh" ধ্বনি হয়, শুধু s নয় - এটি ভুলে যাওয়া।',
  'Dotted version adds one dot above; both pairs are heavy sounds.': 'বিন্দুযুক্ত রূপে উপরে একটি বিন্দু যোগ হয়; দুই জোড়াই ভারী ধ্বনি।',
  'Making heavy letters too light and losing Quranic weight.': 'ভারী হরফকে বেশি হালকা করে কুরআনিক ভার হারানো।',
  'Dot difference plus articulation shift.': 'বিন্দুর পার্থক্যের সাথে উচ্চারণস্থানের পরিবর্তন।',
  'Collapsing ق into ك when reciting quickly.': 'দ্রুত তিলাওয়াতে ق-কে ك-এর সাথে মিশিয়ে ফেলা।',

  'Deep throat': 'গলার গভীর অংশ',
  'Tongue tip and blade': 'জিহ্বার আগা ও ধার',
  'Mid/back tongue': 'জিহ্বার মধ্য/পেছন অংশ',
  'Lips and airflow': 'ঠোঁট ও বায়ুপ্রবাহ',
  'Open the throat gently and avoid squeezing.': 'গলা নরমভাবে খুলুন এবং চেপে ধরা এড়ান।',
  'Do not replace ع or ح with a flat English sound.': 'ع বা ح-কে সমতল ইংরেজি ধ্বনিতে বদলাবেন না।',
  'Use precise tongue placement near the upper teeth/ridge.': 'ওপরের দাঁত/মাড়ির কাছে জিহ্বার অবস্থান নির্ভুল রাখুন।',
  'Do not blur ث with س or ذ with ز.': 'ث-কে س বা ذ-কে ز-এর সাথে গুলিয়ে ফেলবেন না।',
  'Lift middle or back of tongue depending on the letter.': 'হরফ অনুযায়ী জিহ্বার মধ্য বা পেছন অংশ উঠান।',
  'Keep ق deeper than ك.': 'ق-এর ধ্বনি ك-এর চেয়ে গভীর রাখুন।',
  'Use clear lip closure/opening and controlled air release.': 'ঠোঁটের বন্ধ/খোলা স্পষ্ট রাখুন এবং বায়ু ছাড়া নিয়ন্ত্রিত করুন।',
  'For ف, touch lower lip to upper teeth lightly.': 'ف উচ্চারণে নিচের ঠোঁটকে ওপরের দাঁতে হালকা ছোঁয়ান।',

  'Kasra on baa and sukoon on seen.': 'বা-তে কাসরা এবং সীন-এ সুকুন।',
  'Qaaf sound depth and clean sukoon on laam.': 'ক্বাফের গভীর ধ্বনি এবং লামে পরিষ্কার সুকুন।',
  'Strong baa closure and clear consonant ending.': 'বা-তে দৃঢ় বন্ধ এবং স্পষ্ট ব্যঞ্জন-সমাপ্তি।',
  'Damma on noon and smooth transition to waaw.': 'নূনে দাম্মা এবং ওয়াও-এ মসৃণ রূপান্তর।',
  'Differentiate kh sound from plain h.': 'খ ধ্বনিকে সাধারণ h থেকে আলাদা করুন।',

  'Rapid recognition drill (2 min)': 'দ্রুত শনাক্তকরণ ড্রিল (২ মিনিট)',
  'Point to 15 random letters and name each within two seconds. Repeat missed letters twice.': 'এলোমেলো ১৫টি হরফে ইশারা করে প্রতিটির নাম ২ সেকেন্ডে বলুন। ভুলগুলো দুইবার পুনরাবৃত্তি করুন।',
  'Comparison drill (2 min)': 'তুলনা ড্রিল (২ মিনিট)',
  'Alternate pairs: ب/ت/ث, ج/ح/خ, د/ذ, ر/ز, س/ش, ص/ض, ط/ظ, ع/غ, ف/ق.': 'জোড়াগুলো পালাক্রমে পড়ুন: ب/ت/ث, ج/ح/خ, د/ذ, ر/ز, س/ش, ص/ض, ط/ظ, ع/غ, ف/ق।',
  'Pronunciation drill (3 min)': 'উচ্চারণ ড্রিল (৩ মিনিট)',
  'Recite one short set from each articulation zone slowly while monitoring mouth position.': 'মুখের অবস্থান দেখে প্রতিটি উচ্চারণস্থান থেকে একটি ছোট সেট ধীরে পড়ুন।',
  'Harakat drill (3 min)': 'হারাকাত ড্রিল (৩ মিনিট)',
  'Read each pattern row: fatha, kasra, damma, sukoon. Keep rhythm steady and vowels crisp.': 'প্রতিটি প্যাটার্ন সারি পড়ুন: ফাতহা, কাসরা, দাম্মা, সুকুন। ছন্দ স্থির ও স্বর স্পষ্ট রাখুন।',
  'Mini reading check (2 min)': 'ছোট পাঠ যাচাই (২ মিনিট)',
  'Read five beginner examples and identify the key rule used in each word.': 'পাঁচটি প্রাথমিক উদাহরণ পড়ুন এবং প্রতিটি শব্দে ব্যবহৃত মূল নিয়ম শনাক্ত করুন।',
  'Fatha = short a': 'ফাতহা = ছোট a',
  'Kasra = short i': 'কাসরা = ছোট i',
  'Damma = short u': 'দাম্মা = ছোট u',
  'Sukoon = stop/closed': 'সুকুন = থামা/বন্ধ',

  // Pronunciation basics unit deep-localization coverage.
  '1) Heavy vs Light Contrast Grid': '১) ভারী বনাম হালকা ধ্বনি তুলনা গ্রিড',
  '2) Articulation and Posture Indicators': '২) উচ্চারণ ও ভঙ্গি নির্দেশক',
  '3) Madd Timing and Vowel Length Control': '৩) মাদ্দের সময়মাত্রা ও স্বরদৈর্ঘ্য নিয়ন্ত্রণ',
  '4) Pause and Restart Guidance': '৪) থামা ও পুনরারম্ভ নির্দেশনা',
  '5) Rhythm and Flow Drills': '৫) ছন্দ ও প্রবাহ ড্রিল',
  '6) Applied Phrase Practice': '৬) প্রয়োগভিত্তিক ফ্রেজ অনুশীলন',
  'Heavy vs light contrast': 'ভারী বনাম হালকা ধ্বনি তুলনা',
  'Posture and articulation cues': 'ভঙ্গি ও উচ্চারণ নির্দেশনা',
  'Madd timing control': 'মাদ্দের সময়মাত্রা নিয়ন্ত্রণ',
  'Stopping without extra vowels': 'অতিরিক্ত স্বর ছাড়া থামা',
  'Restart consistency': 'পুনরারম্ভের ধারাবাহিকতা',
  'Applied phrase drills': 'প্রয়োগভিত্তিক ফ্রেজ ড্রিল',
  'Revision and self-check': 'রিভিশন ও স্ব-মূল্যায়ন',
  'Follow this order to build clarity, control, and confident recitation flow.': 'স্বচ্ছতা, নিয়ন্ত্রণ এবং আত্মবিশ্বাসী তিলাওয়াতের প্রবাহ গড়তে এই ক্রম অনুসরণ করুন।',
  'Train contrasts before speed. Correct distinction here prevents long-term pronunciation errors.': 'গতি বাড়ানোর আগে পার্থক্য অনুশীলন করুন। এখানে সঠিক পার্থক্য দীর্ঘমেয়াদি উচ্চারণভুল রোধ করে।',
  'Use these indicators while reciting so your sound source remains stable.': 'তিলাওয়াতের সময় এই নির্দেশকগুলো ব্যবহার করুন, যাতে ধ্বনির উৎস স্থিতিশীল থাকে।',
  'Practice natural madd with fixed timing. The goal is consistency, not exaggeration.': 'নির্দিষ্ট সময়মাত্রায় প্রাকৃতিক মাদ্দ অনুশীলন করুন। লক্ষ্য অতিরঞ্জন নয়, ধারাবাহিকতা।',
  'Stopping and restarting cleanly protects meaning and improves recitation confidence.': 'পরিষ্কারভাবে থামা ও পুনরারম্ভ করা অর্থ রক্ষা করে এবং তিলাওয়াতে আত্মবিশ্বাস বাড়ায়।',
  'These drills join pronunciation with rhythm so clarity remains under continuous reading.': 'এই ড্রিলগুলো উচ্চারণকে ছন্দের সাথে যুক্ত করে, যাতে ধারাবাহিক পাঠেও স্বচ্ছতা বজায় থাকে।',
  'Use short Quran phrases to combine contrasts, madd, and pause control in context.': 'ছোট কুরআনি ফ্রেজ ব্যবহার করে প্রেক্ষিতসহ পার্থক্য, মাদ্দ এবং বিরতি-নিয়ন্ত্রণ একত্র করুন।',
  'Qaaf is deeper from the back of tongue; kaaf is lighter.': 'ক্বাফ জিহ্বার পেছন দিক থেকে গভীরভাবে উচ্চারিত হয়; কাফ তুলনামূলক হালকা।',
  'Keep qaaf full and back-focused. Do not flatten it into kaaf.': 'ক্বাফের ধ্বনি পূর্ণ ও পেছনমুখী রাখুন। এটিকে কাফের মতো সমতল করবেন না।',
  'Saad is heavy and fuller; seen stays thin and forward.': 'সাদ ভারী ও ভরাট; সীন হালকা ও সামনের দিকে থাকে।',
  'Darken saad slightly, but avoid over-pressing the jaw.': 'সাদের ধ্বনি সামান্য গাঢ় করুন, তবে চোয়ালে অতিরিক্ত চাপ দেবেন না।',
  'Taa-heavy carries weight; regular taa is lighter and clear.': 'ভারী তা ধ্বনিতে ওজন থাকে; সাধারণ তা হালকা ও স্পষ্ট।',
  'For ط, keep tongue contact firm and release with a fuller tone.': 'ط উচ্চারণে জিহ্বার সংযোগ দৃঢ় রাখুন এবং ভরাট স্বরে ছাড়ুন।',
  'Zaa-heavy keeps thickness, while zay is narrow and lighter.': 'ভারী যা ধ্বনিতে ঘনত্ব থাকে, আর যায় ধ্বনি তুলনামূলক সরু ও হালকা।',
  'Do not let ظ collapse into ز during fast recitation.': 'দ্রুত তিলাওয়াতে ظ-কে ز-এর সাথে মিশে যেতে দেবেন না।',
  'Haa (ح) is deeper breath from throat; haa (ه) is lighter.': 'হা (ح) গলা থেকে গভীর শ্বাস-ধ্বনি; হা (ه) তুলনামূলক হালকা।',
  'Avoid substituting both with the same English-style h sound.': 'দুটোকেই একই ইংরেজি ধাঁচের h ধ্বনিতে প্রতিস্থাপন করবেন না।',
  'Dhaal has softer, front-edge release than daal.': 'যাল (ذ)-এর ধ্বনি দাল (د)-এর চেয়ে নরম ও সামনের প্রান্ত থেকে ছাড়ে।',
  'Place tongue near upper teeth for ذ, not fully behind ridge like د.': 'ذ-এর জন্য জিহ্বা ওপরের দাঁতের কাছে রাখুন; د-এর মতো পুরোপুরি মাড়ির পেছনে নয়।',
  'Jaw relaxation': 'চোয়াল শিথিলতা',
  'steady opening': 'স্থিতিশীল খোলা অবস্থা',
  'Keep jaw naturally open without stiffness during long sounds.': 'দীর্ঘ ধ্বনির সময় চোয়াল স্বাভাবিকভাবে খোলা রাখুন, শক্ত করে নয়।',
  'Do not lock jaw; tension distorts heavy/light contrast.': 'চোয়াল লক করবেন না; চাপ ভারী/হালকা পার্থক্য বিকৃত করে।',
  'Tongue precision': 'জিহ্বার নিখুঁততা',
  'clean contact points': 'পরিষ্কার সংস্পর্শ বিন্দু',
  'Touch exact articulation points briefly and release cleanly.': 'সুনির্দিষ্ট উচ্চারণস্থানে সংক্ষিপ্ত স্পর্শ দিন এবং পরিষ্কারভাবে ছাড়ুন।',
  'Do not drag tongue placement across nearby letters.': 'কাছাকাছি হরফে জিহ্বার অবস্থান টেনে নিয়ে যাবেন না।',
  'Lip control': 'ঠোঁটের নিয়ন্ত্রণ',
  'clear rounding/closure': 'স্পষ্ট গোলাকৃতি/বন্ধ',
  'Round for damma sounds and close fully for baa/meem stops.': 'দাম্মা ধ্বনিতে ঠোঁট গোল করুন এবং বা/মীমে পূর্ণভাবে বন্ধ করুন।',
  'Do not leak air at lip closures.': 'ঠোঁট বন্ধের সময় বাতাস বের হতে দেবেন না।',
  'Airflow balance': 'বায়ুপ্রবাহের ভারসাম্য',
  'smooth breath stream': 'মসৃণ শ্বাসপ্রবাহ',
  'Maintain even airflow across phrases.': 'ফ্রেজ জুড়ে সমান বায়ুপ্রবাহ বজায় রাখুন।',
  'Avoid sudden force bursts that break rhythm.': 'হঠাৎ জোরে বায়ু ছেড়ে ছন্দ ভেঙে ফেলবেন না।',
  'Voice tone': 'কণ্ঠস্বরের টোন',
  'stable loudness': 'স্থিতিশীল উচ্চতার মাত্রা',
  'Use moderate tone for clarity and control.': 'স্বচ্ছতা ও নিয়ন্ত্রণের জন্য মাঝারি টোন ব্যবহার করুন।',
  'Do not shout heavy letters or whisper light letters.': 'ভারী হরফ চিৎকার করে বা হালকা হরফ ফিসফিসিয়ে পড়বেন না।',
  'Natural madd with alif': 'আলিফসহ প্রাকৃতিক মাদ্দ',
  'Natural madd with yaa': 'ইয়াসহ প্রাকৃতিক মাদ্দ',
  'Natural madd with waaw': 'ওয়াওসহ প্রাকৃতিক মাদ্দ',
  'Madd in phrase flow': 'ফ্রেজের প্রবাহে মাদ্দ',
  '2 beats': '২ মাত্রা',
  '2 beats each': 'প্রতিটিতে ২ মাত্রা',
  'Count evenly: 1-2, without stretching beyond control.': 'সমানভাবে ১-২ গণুন, নিয়ন্ত্রণের বাইরে টানবেন না।',
  'Keep tone stable from start to end of the vowel.': 'স্বরধ্বনির শুরু থেকে শেষ পর্যন্ত টোন স্থির রাখুন।',
  'Round lips lightly and avoid collapsing into a short u.': 'ঠোঁট হালকা গোল করুন এবং ছোট u-তে ভেঙে যাওয়া এড়ান।',
  'Do not speed up the second syllable after a madd.': 'মাদ্দের পরে দ্বিতীয় সিলেবল দ্রুত করবেন না।',
  'Stop on sukoon-like ending': 'সুকুনসদৃশ সমাপ্তিতে থামুন',
  'End with a clean consonant stop.': 'পরিষ্কার ব্যঞ্জন-সমাপ্তিতে থামুন।',
  'Restart from the nearest complete word.': 'নিকটতম পূর্ণ শব্দ থেকে পুনরারম্ভ করুন।',
  'No extra vowel at stop': 'থামার সময় অতিরিক্ত স্বর নয়',
  'Cut sound cleanly without adding "uh".': '"uh" না যোগ করে ধ্বনি পরিষ্কারভাবে বন্ধ করুন।',
  'Resume with clear first syllable.': 'স্পষ্ট প্রথম সিলেবল দিয়ে আবার শুরু করুন।',
  'Planned breath pause': 'পরিকল্পিত শ্বাস-বিরতি',
  'Pause at phrase boundary, not middle of attached meaning.': 'অর্থসংযুক্ত অংশের মাঝখানে নয়, ফ্রেজের সীমানায় বিরতি নিন।',
  'Take one calm breath, then restart with same tempo.': 'একবার শান্তভাবে শ্বাস নিন, তারপর একই গতিতে শুরু করুন।',
  'Restart with tone continuity': 'টোনের ধারাবাহিকতায় পুনরারম্ভ',
  'Finish line at comfortable tone.': 'লাইন স্বাচ্ছন্দ্যপূর্ণ টোনে শেষ করুন।',
  'Restart with similar loudness and rhythm.': 'সমজাতীয় উচ্চতা ও ছন্দে পুনরায় শুরু করুন।',
  'Avoid restarting too loud after quiet stop.': 'নরম বিরতির পর হঠাৎ খুব জোরে শুরু করবেন না।',
  '2-beat pacing drill': '২-মাত্রার গতি ড্রিল',
  'Read one short line at slow pace.': 'একটি ছোট লাইন ধীর গতিতে পড়ুন।',
  'Tap two beats for each natural madd.': 'প্রতিটি প্রাকৃতিক মাদ্দে দুই মাত্রা টোকা দিন।',
  'Repeat three times with same tempo.': 'একই গতিতে তিনবার পুনরাবৃত্তি করুন।',
  'Build consistent timing and prevent rushing.': 'ধারাবাহিক সময়মাত্রা গড়ুন এবং তাড়াহুড়ো রোধ করুন।',
  'Contrast chain drill': 'পার্থক্য-শৃঙ্খল ড্রিল',
  'Recite ق ك ق ك slowly.': 'ق ك ق ك ধীরে তিলাওয়াত করুন।',
  'Repeat with ص س ص س and ط ت ط ت.': 'তারপর ص س ص س এবং ط ت ط ت দিয়ে পুনরাবৃত্তি করুন।',
  'Use mirror or audio feedback for clarity.': 'স্বচ্ছতার জন্য আয়না বা অডিও ফিডব্যাক ব্যবহার করুন।',
  'Lock heavy/light distinction under repetition.': 'পুনরাবৃত্তির মধ্যে ভারী/হালকা পার্থক্য স্থির করুন।',
  'Stop-release drill': 'থামা-ছাড়া ড্রিল',
  'Read 5 words ending with sukoon.': 'সুকুনে শেষ হয় এমন ৫টি শব্দ পড়ুন।',
  'Stop each word cleanly without echo vowel.': 'প্রতিটি শব্দ প্রতিধ্বনি স্বর ছাড়া পরিষ্কারভাবে থামান।',
  'Restart each word with steady tone.': 'প্রতিটি শব্দ স্থির টোনে পুনরায় শুরু করুন।',
  'Improve ending clarity and restart confidence.': 'সমাপ্তির স্বচ্ছতা ও পুনরারম্ভের আত্মবিশ্বাস উন্নত করুন।',
  'Single-breath phrase drill': 'এক-শ্বাস ফ্রেজ ড্রিল',
  'Choose one short ayah phrase.': 'একটি ছোট আয়াত-ফ্রেজ নির্বাচন করুন।',
  'Read in one controlled breath at medium speed.': 'মধ্যম গতিতে নিয়ন্ত্রিত এক শ্বাসে পড়ুন।',
  'Repeat while preserving pronunciation quality.': 'উচ্চারণের মান বজায় রেখে পুনরাবৃত্তি করুন।',
  'Strengthen flow without sacrificing letter accuracy.': 'হরফের শুদ্ধতা বজায় রেখে প্রবাহ শক্তিশালী করুন।',
  'Qaaf depth, clean sukoon on laam, and balanced flow.': 'ক্বাফের গভীরতা, লামে পরিষ্কার সুকুন, এবং ভারসাম্যপূর্ণ প্রবাহ।',
  'Natural madd timing and smooth transition after hamzah.': 'প্রাকৃতিক মাদ্দের সময়মাত্রা এবং হামযার পরে মসৃণ রূপান্তর।',
  'Controlled stop/release and clear kh sound.': 'নিয়ন্ত্রিত থামা/ছাড়া এবং স্পষ্ট খ ধ্বনি।',
  'Heavy/light contrast and stable phrase pacing.': 'ভারী/হালকা পার্থক্য এবং স্থিতিশীল ফ্রেজ-গতি।',
  'Yaa madd count and rounded waaw sound.': 'ইয়া মাদ্দের গণনা এবং গোলাকার ওয়াও ধ্বনি।',
  'Contrast warm-up': 'পার্থক্য ওয়ার্ম-আপ',
  'Recite three heavy/light pairs in slow and medium speed.': 'ধীর ও মধ্যম গতিতে তিনটি ভারী/হালকা জোড়া তিলাওয়াত করুন।',
  'Posture check': 'ভঙ্গি যাচাই',
  'Review jaw, tongue, and lip cues before practice line.': 'অনুশীলন লাইনের আগে চোয়াল, জিহ্বা ও ঠোঁটের নির্দেশনা পর্যালোচনা করুন।',
  'Madd count check': 'মাদ্দ গণনা যাচাই',
  'Read one line and hold each natural madd for exactly 2 beats.': 'একটি লাইন পড়ে প্রতিটি প্রাকৃতিক মাদ্দ ঠিক ২ মাত্রা ধরে রাখুন।',
  'Pause-restart check': 'থামা-পুনরারম্ভ যাচাই',
  'Do two deliberate stops and restart each phrase clearly.': 'দুটি সচেতন বিরতি নিন এবং প্রতিটি ফ্রেজ স্পষ্টভাবে পুনরারম্ভ করুন।',
  'Self-record review': 'স্ব-রেকর্ড রিভিউ',
  'Record 30 seconds and note one strength plus one correction.': '৩০ সেকেন্ড রেকর্ড করুন এবং একটি শক্তি ও একটি সংশোধনের পয়েন্ট লিখুন।',

  // Makharij unit deep-localization coverage.
  '1) Articulation Zone Map': '১) উচ্চারণস্থান (মাখরাজ) মানচিত্র',
  '2) Confusion Pair Corrections': '২) বিভ্রান্তিকর জোড়া সংশোধন',
  '3) Guided Makharij Drills': '৩) নির্দেশিত মাখারিজ ড্রিল',
  '4) Applied Phrase Practice': '৪) প্রয়োগভিত্তিক ফ্রেজ অনুশীলন',
  '5) Revision and Mastery Checklist': '৫) রিভিশন ও দক্ষতা চেকলিস্ট',
  'Move in this order to build articulation precision from zone awareness to real phrase recitation.': 'উচ্চারণস্থান-সচেতনতা থেকে বাস্তব ফ্রেজ তিলাওয়াত পর্যন্ত উচ্চারণের নিখুঁততা গড়তে এই ক্রম অনুসরণ করুন।',
  'Learn each makhraj zone with its letters, physical cue, and a quick corrective drill.': 'প্রতিটি মাখরাজ জোন তার হরফ, শারীরিক নির্দেশনা এবং দ্রুত সংশোধনী ড্রিলসহ শিখুন।',
  'Use pair comparisons to protect articulation identity under real recitation pace.': 'বাস্তব তিলাওয়াতের গতিতে উচ্চারণের স্বাতন্ত্র্য বজায় রাখতে জোড়াভিত্তিক তুলনা ব্যবহার করুন।',
  'These structured drills build consistency from isolated letters into connected delivery.': 'এই কাঠামোবদ্ধ ড্রিলগুলো পৃথক হরফ থেকে সংযুক্ত তিলাওয়াতে ধারাবাহিকতা গড়ে তোলে।',
  'Apply makharij precision in short Quran phrases so articulation remains clear in context.': 'প্রেক্ষিতভিত্তিক স্বচ্ছ উচ্চারণ বজায় রাখতে ছোট কুরআনি ফ্রেজে মাখারিজের নিখুঁততা প্রয়োগ করুন।',
  'Use this review block daily to lock articulation precision into regular recitation.': 'নিয়মিত তিলাওয়াতে উচ্চারণের নিখুঁততা স্থায়ী করতে প্রতিদিন এই রিভিউ ব্লকটি ব্যবহার করুন।',
  'Map the articulation zones': 'উচ্চারণস্থানগুলো মানচিত্রে সাজান',
  'Master throat letters': 'গলার হরফগুলো আয়ত্ত করুন',
  'Stabilize tongue-based sounds': 'জিহ্বাভিত্তিক ধ্বনিগুলো স্থিতিশীল করুন',
  'Control lips and ghunnah': 'ঠোঁট ও গুন্নাহ নিয়ন্ত্রণ করুন',
  'Correct confusion pairs': 'বিভ্রান্তিকর জোড়াগুলো সংশোধন করুন',
  'Apply in Quran phrases': 'কুরআনি ফ্রেজে প্রয়োগ করুন',
  'Review and self-check': 'রিভিউ ও স্ব-মূল্যায়ন করুন',
  'Deep throat (aqsa al-halq)': 'গলার গভীর অংশ (আকসা আল-হালক)',
  'From the deepest throat origin.': 'গলার সবচেয়ে গভীর উৎস থেকে উচ্চারণ করুন।',
  'Start cleanly without adding extra glide.': 'অতিরিক্ত স্লাইড না যোগ করে স্পষ্টভাবে শুরু করুন।',
  'Weak hamzah onset or breathy, unclear haa.': 'হামযার শুরু দুর্বল হওয়া বা ه ধ্বনি শ্বাসময় ও অস্পষ্ট হওয়া।',
  'Middle throat (wasat al-halq)': 'গলার মধ্যভাগ (ওয়াসাত আল-হালক)',
  'From the mid-throat area with open passage.': 'খোলা প্রবাহ রেখে গলার মধ্যভাগ থেকে উচ্চারণ করুন।',
  'Keep controlled depth and stable airflow.': 'নিয়ন্ত্রিত গভীরতা ও স্থিতিশীল বায়ুপ্রবাহ বজায় রাখুন।',
  'Reading ع as flat vowel or ح as regular h.': 'ع-কে সমতল স্বরধ্বনি বা ح-কে সাধারণ h হিসেবে পড়া।',
  'Upper throat (adna al-halq)': 'গলার উপরের অংশ (আদনা আল-হালক)',
  'Near upper throat toward mouth entrance.': 'মুখের প্রবেশমুখের দিকে গলার উপরের অংশে।',
  'Use textured friction without over-force.': 'অতিরিক্ত চাপ ছাড়া ঘর্ষণধর্মী ধ্বনি ব্যবহার করুন।',
  'Turning خ into soft h or collapsing غ sound.': 'خ-কে নরম h বানিয়ে ফেলা বা غ ধ্বনি ভেঙে ফেলা।',
  'Back and middle tongue': 'জিহ্বার পেছন ও মধ্যভাগ',
  'Back and center tongue contact points.': 'জিহ্বার পেছন ও মধ্যভাগের সংস্পর্শ-বিন্দু ব্যবহার করুন।',
  'Differentiate depth for ق/ك and spread for ش.': 'ق/ك-তে গভীরতার পার্থক্য এবং ش-তে বিস্তার স্পষ্ট রাখুন।',
  'Reading ق like ك or reducing ش clarity.': 'ق-কে ك-এর মতো পড়া বা ش-এর স্বচ্ছতা কমিয়ে ফেলা।',
  'Tongue tip and edge': 'জিহ্বার আগা ও কিনারা',
  'Tip/blade contacts with teeth and ridge zones.': 'জিহ্বার আগা/ধার দাঁত ও মাড়ির রিজ অঞ্চলে স্পর্শ করে।',
  'Use precise, brief contact then clear release.': 'নির্ভুল ও সংক্ষিপ্ত সংস্পর্শের পর পরিষ্কারভাবে ধ্বনি ছাড়ুন।',
  'Blending heavy and light pairs under speed.': 'দ্রুতগতিতে ভারী ও হালকা জোড়া গুলিয়ে ফেলা।',
  'Lips and nasal cavity': 'ঠোঁট ও নাসিকাগহ্বর',
  'ف ب م و + ghunnah': 'ف ب م و + গুন্নাহ',
  'Lip closure/rounding and nasal resonance support.': 'ঠোঁট বন্ধ/গোল করা এবং নাসিক্য অনুরণনের সহায়তা।',
  'Seal lips fully for ب/م and keep ف airy but sharp.': 'ب/م-এ ঠোঁট পুরোপুরি বন্ধ করুন এবং ف-এ বায়ুপ্রবাহ হালকা হলেও ধারালো রাখুন।',
  'Air leak on lip letters and unstable ghunnah.': 'ঠোঁটের হরফে বাতাস লিক হওয়া এবং অস্থির গুন্নাহ।',
  'Qaaf is deeper from back tongue; kaaf is lighter and fronted.': 'ক্বাফ জিহ্বার পেছন দিক থেকে গভীর; কাফ হালকা ও সামনের দিকে।',
  'قَ كَ قَ كَ in slow and medium rounds.': 'ধীর ও মধ্যম গতিতে قَ كَ قَ كَ অনুশীলন করুন।',
  'Do not flatten ق into ك.': 'ق-কে ك-এর মতো সমতল করে ফেলবেন না।',
  'Seen stays light; saad carries heaviness and fuller resonance.': 'সীন হালকা থাকে; সাদ ভারী ও ভরাট অনুরণন বহন করে।',
  'سَ صَ سِ صِ in paired cycles.': 'জোড়াভিত্তিক চক্রে سَ صَ سِ صِ অনুশীলন করুন।',
  'Avoid reading ص with thin tone.': 'ص-কে পাতলা টোনে পড়া এড়িয়ে চলুন।',
  'Taa is light; taa-heavy requires fuller pressure and tone.': 'তা হালকা; ভারী ط-এ বেশি ভর ও পূর্ণ টোন প্রয়োজন।',
  'تَ طَ تُ طُ with equal pacing.': 'সমান গতিতে تَ طَ تُ طُ অনুশীলন করুন।',
  'Do not over-press ط into harsh sound.': 'অতিরিক্ত চাপ দিয়ে ط-কে কর্কশ করবেন না।',
  'Dhaal uses softer front-edge release than daal.': 'যাল (ذ)-এর ছাড়া দাল (د)-এর তুলনায় নরম ও সামনের প্রান্তে।',
  'دَ ذَ دِ ذِ with tongue-position awareness.': 'জিহ্বার অবস্থান সচেতন রেখে دَ ذَ دِ ذِ অনুশীলন করুন।',
  'Do not replace ذ with ز or د.': 'ذ-কে ز বা د দিয়ে প্রতিস্থাপন করবেন না।',
  'ح / ه and ع / ء': 'ح / ه এবং ع / ء',
  'ح and ع are deeper throat sounds than ه and ء.': 'ح ও ع, ه ও ء-র তুলনায় গভীর গলার ধ্বনি।',
  'حَ هَ | عَ ءَ while preserving depth contrast.': 'গভীরতার পার্থক্য রেখে حَ هَ | عَ ءَ অনুশীলন করুন।',
  'Avoid merging both pairs into one sound quality.': 'দুই জোড়াকে এক ধরনের ধ্বনিতে মিশিয়ে ফেলবেন না।',
  'Zone sweep drill': 'জোন সুইপ ড্রিল',
  'Read one sample from each makhraj zone.': 'প্রতিটি মাখরাজ জোন থেকে একটি নমুনা পড়ুন।',
  'Pause 1 second between zones to reset articulation.': 'উচ্চারণ রিসেট করতে প্রতিটি জোনের মাঝে ১ সেকেন্ড বিরতি নিন।',
  'Repeat full sweep three times with equal clarity.': 'সমান স্বচ্ছতা রেখে পূর্ণ সুইপ তিনবার পুনরাবৃত্তি করুন।',
  'Build zone awareness and consistent letter identity.': 'জোন-সচেতনতা ও হরফের ধারাবাহিক স্বাতন্ত্র্য তৈরি করুন।',
  'Throat precision drill': 'গলা-নিখুঁততা ড্রিল',
  'Recite ء ه ع ح غ خ in slow sequence.': 'ধীরে ক্রমানুসারে ء ه ع ح غ خ তিলাওয়াত করুন।',
  'Repeat each pair twice before moving on.': 'এগোনোর আগে প্রতিটি জোড়া দুইবার পুনরাবৃত্তি করুন।',
  'Record and compare depth and friction quality.': 'রেকর্ড করে গভীরতা ও ঘর্ষণধ্বনির মান তুলনা করুন।',
  'Stabilize throat-origin distinctions.': 'গলা-উৎসভিত্তিক পার্থক্য স্থিতিশীল করুন।',
  'Tongue placement ladder': 'জিহ্বার অবস্থান ধাপ-ড্রিল',
  'Run ق/ك, س/ص, ت/ط, د/ذ sequence.': 'ق/ك, س/ص, ت/ط, د/ذ ক্রমে অনুশীলন করুন।',
  'Maintain same tempo for each pair.': 'প্রতিটি জোড়ায় একই গতি বজায় রাখুন।',
  'Repeat at medium speed without losing contrast.': 'পার্থক্য না হারিয়ে মধ্যম গতিতে পুনরাবৃত্তি করুন।',
  'Keep precision when pace increases.': 'গতি বাড়লেও নিখুঁততা ধরে রাখুন।',
  'Lip and ghunnah control drill': 'ঠোঁট ও গুন্নাহ নিয়ন্ত্রণ ড্রিল',
  'Read ف ب م و sets with clear lip motion.': 'ঠোঁটের স্পষ্ট নড়াচড়া রেখে ف ب م و সেট অনুশীলন করুন।',
  'Add noon-meem ghunnah for two-count hum.': 'দুই মাত্রার গুঞ্জনসহ নূন-মীম গুন্নাহ যোগ করুন।',
  'فَ بَ مَ وَ | مّ نّ (ghunnah)': 'فَ بَ مَ وَ | مّ نّ (গুন্নাহ)',
  'Blend into one short phrase recitation.': 'এগুলো মিলিয়ে একটি ছোট ফ্রেজ তিলাওয়াতে আনুন।',
  'Coordinate lips, airflow, and nasal resonance.': 'ঠোঁট, বায়ুপ্রবাহ ও নাসিক্য অনুরণন সমন্বয় করুন।',
  'Kh articulation and clean shaddah emphasis.': 'খ ধ্বনির উচ্চারণ এবং শাদ্দাহর স্পষ্ট জোর বজায় রাখুন।',
  'Qaaf depth, `ayn onset, and smooth noon transition.': 'ক্বাফের গভীরতা, আইন-এর সূচনা এবং নূনের মসৃণ রূপান্তর।',
  'Yaa clarity, `ayn control, and baa closure.': 'ইয়ার স্বচ্ছতা, আইন-এর নিয়ন্ত্রণ এবং বা-র পূর্ণ বন্ধ।',
  'Ghayn texture and qaaf articulation contrast.': 'গয়নের ঘর্ষণধর্মী ধ্বনি ও ক্বাফের উচ্চারণ-পার্থক্য।',
  'Saad heaviness and dhaal release precision.': 'সাদের ভারী ধ্বনি ও যালের নিখুঁত ছাড়া।',
  'Zone recall': 'জোন পুনঃস্মরণ',
  'Name each zone and read two letters from it.': 'প্রতিটি জোনের নাম বলুন এবং সেখান থেকে দুইটি হরফ পড়ুন।',
  'Pair correction': 'জোড়া সংশোধন',
  'Run 5 confusion pairs and fix weak distinctions.': '৫টি বিভ্রান্তিকর জোড়া অনুশীলন করে দুর্বল পার্থক্যগুলো ঠিক করুন।',
  'Phrase articulation pass': 'ফ্রেজ উচ্চারণ অনুশীলন পাস',
  'Read 3 phrases and mark one target letter each.': '৩টি ফ্রেজ পড়ুন এবং প্রতিটিতে একটি লক্ষ্য হরফ চিহ্নিত করুন।',
  'Audio self-audit': 'অডিও স্ব-মূল্যায়ন',
  'Record 30 seconds and note one articulation improvement.': '৩০ সেকেন্ড রেকর্ড করে উচ্চারণের একটি উন্নয়ন-পয়েন্ট লিখুন।',
  'Final recitation check': 'চূড়ান্ত তিলাওয়াত যাচাই',
  'Recite one short surah with deliberate makharij focus.': 'সচেতন মাখারিজ ফোকাস রেখে একটি ছোট সূরা তিলাওয়াত করুন।',

  // Tajweed rules unit deep-localization coverage.
  '1) Noon Saakin and Tanween Rules': '১) নূন সাকিন ও তানউইনের নিয়ম',
  '2) Meem Saakin Rules': '২) মীম সাকিনের নিয়ম',
  '3) Qalqalah and Madd Control': '৩) কালকালাহ ও মাদ্দ নিয়ন্ত্রণ',
  '4) Waqf and Restart Rules': '৪) ওয়াক্‌ফ ও পুনরারম্ভের নিয়ম',
  '5) Applied Phrase Practice': '৫) প্রয়োগভিত্তিক ফ্রেজ অনুশীলন',
  '6) Revision and Mastery Checklist': '৬) রিভিশন ও দক্ষতা চেকলিস্ট',
  'Follow this sequence to move from rule recognition to full applied recitation.': 'নিয়ম চেনা থেকে পূর্ণ প্রয়োগভিত্তিক তিলাওয়াতে যেতে এই ধারাটি অনুসরণ করুন।',
  'Study izhar, idgham, iqlab, and ikhfa with triggers, examples, and delivery notes.': 'ট্রিগার, উদাহরণ এবং প্রয়োগ-নোটসহ ইযহার, ইদগাম, ইকলাব ও ইখফা শিখুন।',
  'Apply ikhfa shafawi, idgham shafawi, and izhar shafawi inside connected reading.': 'সংযুক্ত তিলাওয়াতের মধ্যে ইখফা শাফাভি, ইদগাম শাফাভি ও ইযহার শাফাভি প্রয়োগ করুন।',
  'Train bounce letters and vowel length discipline together for stable pronunciation quality.': 'উচ্চারণের স্থির মানের জন্য কম্পনধ্বনি ও স্বরদৈর্ঘ্য-শৃঙ্খলা একসাথে অনুশীলন করুন।',
  'Practice safe stopping points and clean restarts to preserve meaning and tajweed quality.': 'অর্থ ও তাজবিদের মান রক্ষায় নিরাপদ থামা এবং পরিষ্কার পুনরারম্ভ অনুশীলন করুন।',
  'Use short Quran phrases to combine rule knowledge into practical recitation.': 'নিয়মের জ্ঞানকে ব্যবহারিক তিলাওয়াতে রূপ দিতে ছোট কুরআনি ফ্রেজ ব্যবহার করুন।',
  'Noon/tanween rules': 'নূন/তানউইনের নিয়ম',
  'Meem saakin rules': 'মীম সাকিনের নিয়ম',
  'Qalqalah control': 'কালকালাহ নিয়ন্ত্রণ',
  'Madd timing': 'মাদ্দের সময়মাত্রা',
  'Waqf and restart': 'ওয়াক্‌ফ ও পুনরারম্ভ',
  'Applied phrase reading': 'প্রয়োগভিত্তিক ফ্রেজ পাঠ',
  'Noon saakin/tanween before throat letters': 'গলার হরফের আগে নূন সাকিন/তানউইন',
  'Pronounce noon/tanween clearly without merging.': 'মিশিয়ে না দিয়ে নূন/তানউইন স্পষ্টভাবে উচ্চারণ করুন।',
  'Keep sound clear and direct, no nasal blending.': 'ধ্বনি স্পষ্ট ও সরাসরি রাখুন; নাসিক্য মিশ্রণ নয়।',
  'Noon saakin/tanween before ي ر م ل و ن': 'ي ر م ل و ن-এর আগে নূন সাকিন/তানউইন',
  'Merge into next letter, with or without ghunnah by type.': 'ধরন অনুযায়ী গুন্নাহসহ বা ছাড়া পরের হরফে মিশিয়ে পড়ুন।',
  'Do not keep noon fully separate in true idgham positions.': 'প্রকৃত ইদগাম অবস্থায় নূনকে পুরো আলাদা রাখবেন না।',
  'Noon saakin/tanween before ب': 'ب-এর আগে নূন সাকিন/তানউইন',
  'Convert noon/tanween into a hidden meem with ghunnah.': 'নূন/তানউইনকে গুন্নাহসহ গোপন মীমে রূপান্তর করুন।',
  'Show ghunnah but avoid exaggerated lip closure.': 'গুন্নাহ প্রকাশ করুন, তবে ঠোঁট অতিরিক্ত চেপে ধরবেন না।',
  'Noon saakin/tanween before remaining ikhfa letters': 'বাকি ইখফা হরফগুলোর আগে নূন সাকিন/তানউইন',
  'Read between izhar and idgham with controlled ghunnah.': 'নিয়ন্ত্রিত গুন্নাহ রেখে ইযহার ও ইদগামের মাঝামাঝি ভঙ্গিতে পড়ুন।',
  'Keep transition smooth; do not fully hide clarity.': 'রূপান্তর মসৃণ রাখুন; স্বচ্ছতা পুরোপুরি আড়াল করবেন না।',
  'Ikhfa Shafawi': 'ইখফা শাফাভি',
  'Idgham Shafawi': 'ইদগাম শাফাভি',
  'Izhar Shafawi': 'ইযহার শাফাভি',
  'Meem saakin before ب': 'ب-এর আগে মীম সাকিন',
  'Hide meem with ghunnah and soft lip readiness.': 'নরম ঠোঁট-প্রস্তুতিসহ গুন্নাহ দিয়ে মীম গোপন করুন।',
  'Do not read full clear meem before baa.': 'বা-এর আগে পূর্ণ স্পষ্ট মীম পড়বেন না।',
  'Meem saakin before م': 'م-এর আগে মীম সাকিন',
  'Merge with ghunnah while maintaining measured timing.': 'পরিমিত সময়মাত্রা বজায় রেখে গুন্নাহসহ মিশিয়ে পড়ুন।',
  'Avoid weak merge or dropping ghunnah.': 'দুর্বল মিশ্রণ বা গুন্নাহ বাদ দেওয়া এড়িয়ে চলুন।',
  'Meem saakin before all other letters': 'অন্যান্য সব হরফের আগে মীম সাকিন',
  'Read meem clearly with full lip closure.': 'ঠোঁট সম্পূর্ণ বন্ধ রেখে মীম স্পষ্টভাবে পড়ুন।',
  'Do not nasalize where izhar shafawi is required.': 'যেখানে ইযহার শাফাভি প্রয়োজন সেখানে নাসিক্য করবেন না।',
  'Stronger at waqf, lighter during continuation': 'ওয়াক্‌ফে বেশি স্পষ্ট, চলমান পাঠে তুলনামূলক হালকা',
  'Notice bounce when letter carries sukoon': 'হরফে সুকুন থাকলে কম্পন লক্ষ্য করুন',
  'Clear in stressed/sukoon contexts': 'জোর বা সুকুন অবস্থায় স্পষ্টভাবে প্রকাশ পায়',
  'Observe controlled bounce at stop': 'থামার সময় নিয়ন্ত্রিত কম্পন লক্ষ্য করুন',
  'Bounce briefly without adding full vowel.': 'পূর্ণ স্বর যোগ না করে সংক্ষিপ্ত কম্পন দিন।',
  'Keep articulation point stable before release.': 'ধ্বনি ছাড়ার আগে উচ্চারণস্থল স্থিতিশীল রাখুন।',
  'Do not over-bounce into an extra syllable.': 'অতিরিক্ত সিলেবল তৈরি করে বেশি কম্পন দেবেন না।',
  'Maintain clarity without harsh impact.': 'কঠোরতা ছাড়া স্বচ্ছতা বজায় রাখুন।',
  'Natural Madd (Madd Asli)': 'প্রাকৃতিক মাদ্দ (মাদ্দ আসলি)',
  'Madd in connected phrases': 'সংযুক্ত ফ্রেজে মাদ্দ',
  'Waqf-influenced length awareness': 'ওয়াক্‌ফভিত্তিক দৈর্ঘ্য-সচেতনতা',
  '2 counts': '২ মাত্রা',
  '2 counts baseline': 'মৌলিকভাবে ২ মাত্রা',
  'Based on stop context': 'থামার প্রেক্ষিতভিত্তিক',
  'Ending words before stop': 'থামার আগে শেষের শব্দসমূহ',
  'Keep count steady and equal across repetitions.': 'পুনরাবৃত্তিতে মাত্রা স্থির ও সমান রাখুন।',
  'Do not shorten madd when recitation speed increases.': 'তিলাওয়াতের গতি বাড়লেও মাদ্দ ছোট করবেন না।',
  'Use teacher-guided moderation; avoid random stretching.': 'শিক্ষক-নির্দেশিত পরিমিতি অনুসরণ করুন; এলোমেলো টান এড়িয়ে চলুন।',
  'Stop at complete meaning unit': 'পূর্ণ অর্থবোধক এককে থামুন',
  'No trailing vowel echo': 'শেষে স্বর-প্রতিধ্বনি টান নয়',
  'Restart with same tone level': 'একই টোনে পুনরারম্ভ করুন',
  'Pause where phrase meaning naturally completes.': 'যেখানে ফ্রেজের অর্থ স্বাভাবিকভাবে সম্পূর্ণ হয় সেখানে থামুন।',
  'Close ending cleanly without adding "uh".': '"uh" যোগ না করে শেষ ধ্বনি পরিষ্কারভাবে বন্ধ করুন।',
  'Finish calmly and keep breath controlled.': 'শান্তভাবে শেষ করুন এবং শ্বাস নিয়ন্ত্রণে রাখুন।',
  'Restart from a coherent word boundary.': 'অর্থপূর্ণ শব্দসীমা থেকে পুনরারম্ভ করুন।',
  'Begin next phrase with clear first syllable.': 'পরবর্তী ফ্রেজ স্পষ্ট প্রথম সিলেবল দিয়ে শুরু করুন।',
  'Resume at similar pitch and speed.': 'প্রায় একই স্বর-উচ্চতা ও গতিতে আবার শুরু করুন।',
  'رَبّ at stop, not rabbu.': 'থামার সময় রَبّ পড়ুন, rabbu নয়।',
  'Avoid sudden loud re-entry after soft stop.': 'নরম বিরতির পর হঠাৎ জোরে পুনরারম্ভ করবেন না।',
  'Ikhfa transition and kh articulation.': 'ইখফার রূপান্তর এবং খ ধ্বনির উচ্চারণ।',
  'Qalqalah at stop and clean waqf handling.': 'থামার সময় কালকালাহ এবং পরিষ্কার ওয়াক্‌ফ প্রয়োগ।',
  'Madd timing and smooth hamzah transition.': 'মাদ্দের সময়মাত্রা এবং হামযার মসৃণ রূপান্তর।',
  'Qalqalah feel and stop discipline.': 'কালকালাহর অনুভব ও থামার শৃঙ্খলা।',
  'Noon/tanween and meem-based transitions.': 'নূন/তানউইন ও মীমভিত্তিক রূপান্তর।',
  'Rule identification': 'নিয়ম শনাক্তকরণ',
  'Label tajweed rule in 8 short examples before reciting.': 'তিলাওয়াতের আগে ৮টি ছোট উদাহরণে তাজবিদের নিয়ম চিহ্নিত করুন।',
  'Noon/meem drill': 'নূন/মীম ড্রিল',
  'Run one cycle each for izhar, idgham, iqlab, ikhfa, and meem rules.': 'ইযহার, ইদগাম, ইকলাব, ইখফা এবং মীমের নিয়মে একটি করে চক্র অনুশীলন করুন।',
  'Qalqalah check': 'কালকালাহ যাচাই',
  'Read 5 qalqalah words at stop and verify bounce control.': 'থামার অবস্থায় ৫টি কালকালাহ শব্দ পড়ে কম্পনের নিয়ন্ত্রণ যাচাই করুন।',
  'Madd and waqf check': 'মাদ্দ ও ওয়াক্‌ফ যাচাই',
  'Recite one ayah with fixed madd count and planned pauses.': 'নির্দিষ্ট মাদ্দ-মাত্রা ও পরিকল্পিত বিরতিসহ একটি আয়াত তিলাওয়াত করুন।',
  'Integrated recitation': 'সমন্বিত তিলাওয়াত',
  'Recite one short surah with active rule awareness and self-review.': 'সক্রিয় নিয়ম-সচেতনতা ও স্ব-মূল্যায়নসহ একটি ছোট সূরা তিলাওয়াত করুন।',
  'Izhar': 'ইযহার',
  'Idgham': 'ইদগাম',
  'Iqlab': 'ইকলাব',
  'Ikhfa': 'ইখফা',
  'مِنْ هَادٍ (min had)': 'مِنْ هَادٍ (মিন হাদ)',
  'مِنْ رَبِّهِمْ (mir rabbihim)': 'مِنْ رَبِّهِمْ (মির রব্বিহিম)',
  'أَنْبِئْهُمْ (ambi hum)': 'أَنْبِئْهُمْ (আম্বি হুম)',
  'مِنْ شَرٍّ (min sharr)': 'مِنْ شَرٍّ (মিন শার্‌র)',
  'الْفَلَقْ (at stop)': 'الْفَلَقْ (থামার সময়)',

  // Word-by-word unit deep-localization coverage.
  'Al-Asr 103:1-3': 'আল-আসর ১০৩:১-৩',
  'Al-Ikhlas 112:1-4': 'আল-ইখলাস ১১২:১-৪',
  'Al-Kawthar 108:1-3': 'আল-কাওসার ১০৮:১-৩',
  'All praise belongs to Allah, Lord of all worlds.': 'সমস্ত প্রশংসা আল্লাহর জন্য, যিনি সব জগতের রব।',
  'Allah (God)': 'আল্লাহ (প্রভু)',
  'Appears in dua, praise, and dependence contexts.': 'দোআ, প্রশংসা ও নির্ভরতার প্রেক্ষিতে ব্যবহৃত হয়।',
  'Appears in trials, worship, and moral growth.': 'পরীক্ষা, ইবাদত ও নৈতিক উন্নতির প্রসঙ্গে আসে।',
  'Attach smoothly to the following word in flow.': 'প্রবাহে পরের শব্দের সাথে মসৃণভাবে যুক্ত করুন।',
  'Break down 3 phrases word by word without translation notes.': 'অনুবাদ নোট ছাড়া ৩টি ফ্রেজ শব্দে শব্দে বিশ্লেষণ করুন।',
  'Central name repeated throughout the Quran.': 'কুরআনজুড়ে বারবার আসা কেন্দ্রীয় নাম।',
  'Connect this root with endurance and worship discipline.': 'এই মূলধাতুকে ধৈর্য ও ইবাদতের শৃঙ্খলার সঙ্গে যুক্ত করুন।',
  'Connected to blessings and obedience.': 'নেয়ামত ও আনুগত্যের সঙ্গে সম্পর্কিত।',
  'Connector scan': 'সংযোজক শনাক্তকরণ',
  'Describes Quran as direction for believers.': 'মুমিনদের জন্য কুরআনকে দিকনির্দেশনা হিসেবে বর্ণনা করে।',
  'Find connector words in one short surah and explain their role.': 'একটি ছোট সূরায় সংযোজক শব্দ খুঁজে তাদের ভূমিকা ব্যাখ্যা করুন।',
  'Forgiveness and covering faults': 'ক্ষমা ও ত্রুটি আচ্ছাদন',
  'Frequently paired with forgiveness and guidance.': 'প্রায়ই ক্ষমা ও হিদায়াতের সাথে যুক্ত থাকে।',
  'Group 10 words into their correct roots and explain core meaning.': '১০টি শব্দ সঠিক মূলধাতুতে গুচ্ছ করে মূল অর্থ ব্যাখ্যা করুন।',
  'Guidance and direction': 'পথনির্দেশ ও দিকনির্দেশ',
  'Guided reflection summary': 'নির্দেশিত প্রতিফলন সারসংক্ষেপ',
  'High-frequency vocabulary': 'বহুল ব্যবহৃত শব্দভান্ডার',
  'Identify declaration words and repeated references to Allah.': 'ঘোষণামূলক শব্দ ও আল্লাহর পুনরাবৃত্ত উল্লেখ শনাক্ত করুন।',
  'Indeed We have granted you abundance.': 'নিশ্চয়ই আমরা তোমাকে প্রাচুর্য দান করেছি।',
  'Indeed/Truly (emphasis)': 'নিশ্চয়/প্রকৃতপক্ষে (জোর)',
  'Knowledge and awareness': 'জ্ঞান ও সচেতনতা',
  'Link it to source/origin meaning in phrase context.': 'ফ্রেজের প্রেক্ষিতে এটিকে উৎস/উৎপত্তির অর্থের সাথে যুক্ত করুন।',
  'Linked with learning, evidence, and humility.': 'শিক্ষা, প্রমাণ ও বিনয়ের সাথে সম্পর্কিত।',
  'Lord, Sustainer': 'রব, প্রতিপালক',
  'Map emphasis particles and command-response flow.': 'জোরপ্রদর্শক পার্টিকল ও নির্দেশ-প্রতিক্রিয়া প্রবাহ মানচিত্রায়ন করুন।',
  'Meaning-led recitation': 'অর্থনির্দেশিত তিলাওয়াত',
  'Mercy and compassionate care': 'রহমত ও সহানুভূতিশীল পরিচর্যা',
  'Notice destination direction in the sentence.': 'বাক্যে গন্তব্যের দিক লক্ষ্য করুন।',
  'Often linked to Judgment, worship, and time reminders.': 'প্রায়ই বিচারদিবস, ইবাদত ও সময়-স্মরণ প্রসঙ্গে ব্যবহৃত হয়।',
  'Patience and steadfastness': 'ধৈর্য ও অবিচলতা',
  'Phrase translation pass': 'ফ্রেজ অনুবাদ অনুশীলন',
  'Phrase-by-phrase breakdown': 'ফ্রেজভিত্তিক বিশ্লেষণ',
  'Read as emphasis marker and identify what is emphasized.': 'এটিকে জোর নির্দেশক হিসেবে পড়ুন এবং কোন বিষয়ে জোর দেওয়া হয়েছে তা শনাক্ত করুন।',
  'Recite one short surah while summarizing each ayah in one sentence.': 'প্রতিটি আয়াত এক বাক্যে সারসংক্ষেপ করতে করতে একটি ছোট সূরা তিলাওয়াত করুন।',
  'Refers to Quran verses and signs in creation.': 'কুরআনের আয়াত ও সৃষ্টির নিদর্শন বোঝাতে ব্যবহৃত হয়।',
  'Review 20 high-frequency words and recall meanings quickly.': '২০টি বহুল ব্যবহৃত শব্দ রিভিউ করে দ্রুত অর্থ স্মরণ করুন।',
  'Root family check': 'মূলধাতু পরিবার যাচাই',
  'Root-family awareness': 'মূলধাতু-পরিবার সচেতনতা',
  'Same root, different patterns; meaning stays in knowledge space.': 'একই মূলধাতু, ভিন্ন রূপ; অর্থ জ্ঞানের পরিসরেই থাকে।',
  'Say: He is Allah, One.': 'বলুন: তিনি আল্লাহ, এক।',
  'Shows a staged order; pause mentally before next idea.': 'ধাপভিত্তিক ক্রম বোঝায়; পরের ভাবনার আগে মানসিক বিরতি নিন।',
  'Sign, verse': 'নিদর্শন, আয়াত',
  'Signals sequence or result; keep transition quick.': 'ধারাবাহিকতা বা ফল নির্দেশ করে; রূপান্তর দ্রুত রাখুন।',
  'So/Then': 'অতএব/তারপর',
  'Then (with delay/order)': 'তারপর (বিরতি/ক্রমসহ)',
  'This root often appears with tawbah and mercy themes.': 'এই মূলধাতু প্রায়ই তাওবা ও রহমতের থিমে আসে।',
  'To/Toward': 'দিকে/অভিমুখে',
  'Track connectors (wa, illa) and key nouns/verbs by role.': 'ভূমিকা অনুযায়ী সংযোজক (wa, illa) ও প্রধান বিশেষ্য/ক্রিয়া অনুসরণ করুন।',
  'Track this root in recitation to notice guidance requests.': 'তিলাওয়াতে এই মূলধাতু অনুসরণ করে হিদায়াতের আবেদনগুলো লক্ষ্য করুন।',
  'Used for faith, revelation, and clarity.': 'ঈমান, ওহি ও স্বচ্ছতার প্রসঙ্গে ব্যবহৃত হয়।',
  'Used for sincerity, understanding, and reform.': 'আন্তরিকতা, বোঝাপড়া ও সংশোধনের প্রসঙ্গে ব্যবহৃত হয়।',
  'Used with belief, trust, and righteous action themes.': 'বিশ্বাস, আস্থা ও সৎকর্মের থিমে ব্যবহৃত হয়।',
  'Vocabulary sprint': 'দ্রুত শব্দভান্ডার অনুশীলন',
  'When this root appears, look for mercy-related meaning.': 'এই মূলধাতু এলে রহমত-সম্পর্কিত অর্থ খুঁজুন।',
  'You alone we worship, and You alone we ask for help.': 'আমরা কেবল আপনারই ইবাদত করি এবং কেবল আপনারই সাহায্য চাই।',
  'إِنَّا (indeed We) | أَعْطَيْنَاكَ (have given you) | الْكَوْثَرَ (abundance)': 'إِنَّا (আমরা অবশ্যই) | أَعْطَيْنَاكَ (আমরা তোমাকে দিয়েছি) | الْكَوْثَرَ (প্রাচুর্য)',
  'إِيَّاكَ (You alone) | نَعْبُدُ (we worship) | وَ (and) | إِيَّاكَ (You alone) | نَسْتَعِينُ (we seek help)': 'إِيَّاكَ (কেবল আপনাকেই) | نَعْبُدُ (আমরা ইবাদত করি) | وَ (এবং) | إِيَّاكَ (কেবল আপনাকেই) | نَسْتَعِينُ (আমরা সাহায্য চাই)',
  'الْحَمْدُ (all praise) | لِلَّهِ (belongs to Allah) | رَبِّ (Lord of) | الْعَالَمِينَ (all worlds)': 'الْحَمْدُ (সমস্ত প্রশংসা) | لِلَّهِ (আল্লাহর জন্য) | رَبِّ (রব) | الْعَالَمِينَ (সমস্ত জগতের)',
  'قُلْ (say) | هُوَ (He is) | اللَّهُ (Allah) | أَحَدٌ (One)': 'قُلْ (বলুন) | هُوَ (তিনি) | اللَّهُ (আল্লাহ) | أَحَدٌ (এক)',

  // Short surah practice unit deep-localization coverage.
  '2 min': '২ মিনিট',
  '3 min': '৩ মিনিট',
  '4 min': '৪ মিনিট',
  'Accuracy check': 'শুদ্ধতা যাচাই',
  'Al-Asr (103)': 'আল-আসর (১০৩)',
  'Al-Asr 103:2-3': 'আল-আসর ১০৩:২-৩',
  'Al-Falaq (113)': 'আল-ফালাক (১১৩)',
  'Al-Falaq 113:1': 'আল-ফালাক ১১৩:১',
  'Al-Fatihah (1)': 'আল-ফাতিহা (১)',
  'Al-Ikhlas (112)': 'আল-ইখলাস (১১২)',
  'Al-Ikhlas 112:1': 'আল-ইখলাস ১১২:১',
  'Al-Kawthar (108)': 'আল-কাওসার (১০৮)',
  'Alternate speed pass': 'বিকল্প গতির পাঠ',
  'An-Naas (114)': 'আন-নাস (১১৪)',
  'An-Naas 114:1-2': 'আন-নাস ১১৪:১-২',
  'Apply correct izhar, idgham, iqlab, or ikhfa behavior.': 'সঠিক ইযহার, ইদগাম, ইকলাব বা ইখফা আচরণ প্রয়োগ করুন।',
  'Apply measured pace in repeated مِنْ شَرِّ pattern.': 'পুনরাবৃত্ত مِنْ شَرِّ ধরণে পরিমিত গতি বজায় রাখুন।',
  'Apply selected tajweed focus points intentionally.': 'নির্বাচিত তাজবিদ ফোকাস-পয়েন্টগুলো সচেতনভাবে প্রয়োগ করুন।',
  'At least 3 target rules are applied correctly.': 'অন্তত ৩টি লক্ষ্য নিয়ম সঠিকভাবে প্রয়োগ হয়েছে।',
  'Audio comparison': 'অডিও তুলনা',
  'Break surah into ayah blocks and practice each block twice.': 'সূরাকে আয়াত-ভাগে ভাগ করে প্রতিটি ভাগ দুইবার অনুশীলন করুন।',
  'Breath check': 'শ্বাস যাচাই',
  'Build continuity without forgetting transitions.': 'রূপান্তর ভুলে না গিয়ে ধারাবাহিকতা গড়ে তুলুন।',
  'Build stable daily salah recitation with correct flow.': 'সঠিক প্রবাহে দৈনিক সালাতের স্থিতিশীল তিলাওয়াত গড়ে তুলুন।',
  'Capture melody, articulation, and pause points.': 'সুর, উচ্চারণ এবং বিরতির পয়েন্ট ধরুন।',
  'Complete 4 short surahs in one continuous confidence session.': 'একটানা আত্মবিশ্বাসী সেশনে ৪টি ছোট সূরা সম্পন্ন করুন।',
  'Complete recitation with no hesitation restarts.': 'দ্বিধা ছাড়া পুনরারম্ভ করে পুরো তিলাওয়াত সম্পন্ন করুন।',
  'Confidence check': 'আত্মবিশ্বাস যাচাই',
  'Control repeated consonant clusters while preserving meaning.': 'অর্থ বজায় রেখে পুনরাবৃত্ত ব্যঞ্জনগুচ্ছ নিয়ন্ত্রণ করুন।',
  'Daily 2-surah cycle': 'দৈনিক ২-সূরা চক্র',
  'Declare Allah as absolutely One.': 'আল্লাহ যে পরম এক, তা ঘোষণা করুন।',
  'Deliver each ayah clearly with confident stop/restart.': 'প্রতিটি আয়াত স্পষ্টভাবে, আত্মবিশ্বাসী থামা/পুনরারম্ভসহ পড়ুন।',
  'Detect and fix missed words, timing, and stops.': 'বাদ পড়া শব্দ, সময়মাত্রা ও বিরতির ভুল শনাক্ত করে সংশোধন করুন।',
  'Divine gift, gratitude, and devotion.': 'আল্লাহপ্রদত্ত দান, কৃতজ্ঞতা ও আনুগত্য।',
  'Do one breath-managed recitation and review weak consonant points.': 'শ্বাস-নিয়ন্ত্রিত একটি তিলাওয়াত করে দুর্বল ব্যঞ্জন পয়েন্টগুলো পর্যালোচনা করুন।',
  'Emphasize repeated النَّاسِ with steady breath and clear articulation.': 'পুনরাবৃত্ত النَّاسِ-এ স্থির শ্বাস ও স্পষ্ট উচ্চারণে জোর দিন।',
  'Evaluate if your short surah recitation is accurate, stable, and prayer-ready.': 'আপনার ছোট সূরা তিলাওয়াত শুদ্ধ, স্থিতিশীল এবং সালাত-উপযোগী কি না তা মূল্যায়ন করুন।',
  'Fluency and breath pacing': 'সাবলীলতা ও শ্বাস-গতি নিয়ন্ত্রণ',
  'Follow meaning units and keep restart tone consistent.': 'অর্থভিত্তিক একক অনুসরণ করুন এবং পুনরারম্ভের টোন একরকম রাখুন।',
  'Highlight transition into exception phrase إِلَّا الَّذِينَ آمَنُوا.': 'ব্যতিক্রম বাক্যাংশ إِلَّا الَّذِينَ آمَنُوا-তে প্রবেশের রূপান্তর স্পষ্ট করুন।',
  'Humanity is in loss except people of faith and action.': 'ঈমান ও আমলকারীরা ছাড়া মানবতা ক্ষতির মধ্যে আছে।',
  'Identify next letter first, then apply rule intentionally.': 'আগে পরের হরফ শনাক্ত করুন, তারপর সচেতনভাবে নিয়ম প্রয়োগ করুন।',
  'Isolate phrases with مِنْ and tanween endings in short surahs.': 'ছোট সূরায় مِنْ এবং তানউইন-শেষ হওয়া ফ্রেজগুলো আলাদা করে অনুশীলন করুন।',
  'Join all ayahs in one smooth recitation pass.': 'সব আয়াত একবারে মসৃণ তিলাওয়াতে যুক্ত করুন।',
  'Keep each ayah distinct with clean endings.': 'প্রতিটি আয়াতকে পরিষ্কার সমাপ্তিসহ স্বতন্ত্র রাখুন।',
  'Keep flow calm and supplicative, especially from أَعُوذُ to رَبِّ.': 'বিশেষ করে أَعُوذُ থেকে رَبِّ পর্যন্ত প্রবাহ শান্ত ও দোআমুখী রাখুন।',
  'Madd discipline': 'মাদ্দের শৃঙ্খলা',
  'Maintain calm, prayer-suitable rhythm.': 'শান্ত ও সালাত-উপযোগী ছন্দ বজায় রাখুন।',
  'Maintain smooth rhythm in protective supplication style.': 'সুরক্ষামূলক দোআর ঢঙে মসৃণ ছন্দ বজায় রাখুন।',
  'Mark safe stops in Al-Fatihah and An-Naas, then recite with plan.': 'আল-ফাতিহা ও আন-নাসে নিরাপদ থামার স্থান চিহ্নিত করে পরিকল্পনা অনুযায়ী তিলাওয়াত করুন।',
  'Mark the shift at إِلَّا with clear contrast in pacing and attention.': 'إِلَّا-তে রূপান্তরকে গতি ও মনোযোগের স্পষ্ট পার্থক্যে চিহ্নিত করুন।',
  'Match pronunciation and timing with model recitation.': 'মডেল তিলাওয়াতের সঙ্গে উচ্চারণ ও সময়মাত্রা মিলিয়ে নিন।',
  'Meaning link pass': 'অর্থ-সংযোগ অনুশীলন',
  'Meaning-linked recitation': 'অর্থ-সংযুক্ত তিলাওয়াত',
  'Memorization cycle': 'মুখস্থ চক্র',
  'Move through this sequence to build memorization, fluency, and salah readiness.': 'মুখস্থ, সাবলীলতা ও সালাত-প্রস্তুতি গড়তে এই ধারাবাহিকতা অনুসরণ করুন।',
  'Natural madd should stay consistent at 2 counts.': 'প্রাকৃতিক মাদ্দ ২ মাত্রায় ধারাবাহিক থাকতে হবে।',
  'No forced mid-word breathing.': 'শব্দের মাঝখানে জোর করে শ্বাস নেবেন না।',
  'Noon/tanween transitions': 'নূন/তানউইন রূপান্তর',
  'Over-bounce that creates an extra syllable.': 'অতিরিক্ত কম্পন দিয়ে বাড়তি সিলেবল তৈরি করা।',
  'Pace check': 'গতি যাচাই',
  'Pause at complete units and restart from coherent boundaries.': 'পূর্ণ অর্থবোধক এককে থামুন এবং সঙ্গত সীমা থেকে পুনরারম্ভ করুন।',
  'Pause mentally on structural shift and continue with stable tone.': 'গঠনগত পরিবর্তনে মানসিক বিরতি নিয়ে স্থির টোনে এগিয়ে যান।',
  'Play one ayah 3 times with full attention.': 'পূর্ণ মনোযোগে একটি আয়াত ৩ বার শুনুন।',
  'Practice ayah-to-ayah transitions without rushing the recurring pattern.': 'পুনরাবৃত্ত ধরণে তাড়াহুড়ো না করে আয়াত-থেকে-আয়াত রূপান্তর অনুশীলন করুন।',
  'Practice key words in Al-Fatihah and Al-Ikhlas with fixed beat count.': 'আল-ফাতিহা ও আল-ইখলাসের মূল শব্দগুলো নির্দিষ্ট মাত্রায় অনুশীলন করুন।',
  'Practice short but precise command-response recitation.': 'সংক্ষিপ্ত কিন্তু নিখুঁত নির্দেশ-প্রতিক্রিয়া তিলাওয়াত অনুশীলন করুন।',
  'Praise, worship, and dua for guidance.': 'প্রশংসা, ইবাদত ও হিদায়াতের দোআ।',
  'Qalqalah at stop': 'থামায় কালকালাহ',
  'Qalqalah letters bounce briefly without added vowel.': 'কালকালাহ হরফে অতিরিক্ত স্বর ছাড়া সংক্ষিপ্ত কম্পন দিন।',
  'Randomly shortening long vowels during faster recitation.': 'দ্রুত তিলাওয়াতে দীর্ঘ স্বর এলোমেলোভাবে ছোট করে ফেলা।',
  'Read 3 rounds and mark one tajweed focus per ayah before final round.': '৩ রাউন্ড পড়ুন এবং শেষ রাউন্ডের আগে প্রতি আয়াতে একটি তাজবিদ ফোকাস চিহ্নিত করুন।',
  'Read each ayah separately, then connect all three in one fluent pass.': 'প্রতিটি আয়াত আলাদা পড়ে পরে তিনটি একত্রে সাবলীলভাবে পড়ুন।',
  'Read one round slow and one round normal salah pace.': 'এক রাউন্ড ধীরে ও এক রাউন্ড স্বাভাবিক সালাতের গতিতে পড়ুন।',
  'Read with confident declaration tone and a clean stop at the end.': 'আত্মবিশ্বাসী ঘোষণামূলক টোনে পড়ুন এবং শেষে পরিষ্কারভাবে থামুন।',
  'Reading all noon/tanween patterns with one style.': 'সব নূন/তানউইন ধরণ এক স্টাইলে পড়ে ফেলা।',
  'Recite all 7 ayahs with balanced pace and stop control.': 'সমন্বিত গতি ও বিরতি নিয়ন্ত্রণে ৭টি আয়াত তিলাওয়াত করুন।',
  'Recite from memory and compare with mushaf/audio.': 'মুখস্থ থেকে তিলাওয়াত করে মুসহাফ/অডিওর সঙ্গে তুলনা করুন।',
  'Recite once in salah simulation standing posture.': 'দাঁড়ানো সালাত-সিমুলেশন ভঙ্গিতে একবার তিলাওয়াত করুন।',
  'Recite once slowly for articulation, then once with salah tempo.': 'উচ্চারণের জন্য একবার ধীরে, তারপর সালাতের গতিতে একবার তিলাওয়াত করুন।',
  'Recite two selected surahs with one tajweed focus each.': 'নির্বাচিত দুই সূরা তিলাওয়াত করুন; প্রতিটিতে একটি করে তাজবিদ ফোকাস রাখুন।',
  'Recite with steady breathing and consistent articulation.': 'স্থিতিশীল শ্বাস ও ধারাবাহিক উচ্চারণে তিলাওয়াত করুন।',
  'Recite without skipping or replacing words.': 'শব্দ বাদ না দিয়ে বা বদল না করে তিলাওয়াত করুন।',
  'Record and compare one surah with a reference reciter.': 'একটি সূরা রেকর্ড করে রেফারেন্স কারির তিলাওয়াতের সঙ্গে তুলনা করুন।',
  'Release quickly and avoid opening into a full vowel sound.': 'দ্রুত ছেড়ে দিন এবং পূর্ণ স্বরধ্বনিতে খুলে যাওয়া এড়ান।',
  'Repeat immediately after audio, one phrase at a time.': 'অডিওর পরপরই একেকটি ফ্রেজ করে পুনরাবৃত্তি করুন।',
  'Revision and mastery': 'রিভিশন ও দক্ষতা',
  'Salah readiness checks': 'সালাত-প্রস্তুতি যাচাই',
  'Secure memory with controlled chunking.': 'নিয়ন্ত্রিত ভাগে অনুশীলন করে মুখস্থ স্থির করুন।',
  'Seek protection in the Lord of daybreak.': 'প্রভাতের রবের কাছে আশ্রয় প্রার্থনা করুন।',
  'Seek refuge in the Lord and King of mankind.': 'মানবজাতির রব ও বাদশাহর কাছে আশ্রয় চান।',
  'Seeking protection from external harms.': 'বাহ্যিক অনিষ্ট থেকে সুরক্ষা প্রার্থনা।',
  'Seeking refuge from hidden whispering harms.': 'গোপন কুমন্ত্রণাজনিত অনিষ্ট থেকে আশ্রয় প্রার্থনা।',
  'Self-check': 'স্ব-মূল্যায়ন',
  'State one key message per ayah before reciting.': 'তিলাওয়াতের আগে প্রতি আয়াতে একটি মূল বার্তা বলুন।',
  'Steady speed from first ayah to last.': 'প্রথম আয়াত থেকে শেষ পর্যন্ত স্থির গতি বজায় রাখুন।',
  'Stopping at weak positions that break meaning.': 'অর্থ ভেঙে যায় এমন দুর্বল স্থানে থেমে যাওয়া।',
  'Strengthen clarity in concise declaration verses.': 'সংক্ষিপ্ত ঘোষণামূলক আয়াতে স্বচ্ছতা জোরদার করুন।',
  'Surah objective map': 'সূরা-উদ্দেশ্য মানচিত্র',
  'Tajweed check': 'তাজবিদ যাচাই',
  'Tajweed focus by surah': 'সূরাভিত্তিক তাজবিদ ফোকাস',
  'Tawheed and absolute oneness of Allah.': 'তাওহীদ ও আল্লাহর পরম একত্ব।',
  'Tie ayah message to your voice so recitation is not only correct, but understood.': 'আয়াতের বার্তাকে কণ্ঠের সাথে যুক্ত করুন, যাতে তিলাওয়াত শুধু শুদ্ধ নয়, বোধগম্যও হয়।',
  'Time, loss, and path of salvation.': 'সময়, ক্ষতি ও মুক্তির পথ।',
  'Train stop endings from Al-Falaq and Al-Masad examples.': 'আল-ফালাক ও আল-মাসাদের উদাহরণ থেকে থামার সমাপ্তি অনুশীলন করুন।',
  'Train the most common recitation errors found in short surah practice.': 'ছোট সূরা অনুশীলনে দেখা সবচেয়ে সাধারণ তিলাওয়াত ভুলগুলো প্রশিক্ষণ দিন।',
  'Train warning-and-exception structure in recitation meaning.': 'তিলাওয়াতের অর্থে সতর্কতা-ও-ব্যতিক্রম কাঠামো অনুশীলন করুন।',
  'Use finger beats and keep count equal across rounds.': 'আঙুলের বিট ব্যবহার করে সব রাউন্ডে মাত্রা সমান রাখুন।',
  'Use planned breathing at natural phrase boundaries.': 'প্রাকৃতিক ফ্রেজ-সীমায় পরিকল্পিতভাবে শ্বাস নিন।',
  'Use this map to understand what each short surah should train in your recitation journey.': 'আপনার তিলাওয়াত যাত্রায় প্রতিটি ছোট সূরা কী প্রশিক্ষণ দেবে তা বুঝতে এই মানচিত্র ব্যবহার করুন।',
  'Use this timed cycle to improve retention without sacrificing pronunciation quality.': 'উচ্চারণের মান নষ্ট না করে মনে রাখা শক্ত করতে এই সময়ভিত্তিক চক্র ব্যবহার করুন।',
  'Weekly mastery check': 'সাপ্তাহিক দক্ষতা যাচাই',
  'Zero word omissions in one full pass.': 'একটি পূর্ণ রাউন্ডে কোনো শব্দ বাদ নয়।',

  // Audio-assisted unit deep-localization coverage.
  '1 listening pass + 2 independent recitations.': '১টি শ্রবণ রাউন্ড + ২টি স্বতন্ত্র তিলাওয়াত।',
  '2 shadow rounds + 1 solo pass.': '২টি শ্যাডো রাউন্ড + ১টি একক রাউন্ড।',
  '3 loop rounds with one self-record.': '১টি স্ব-রেকর্ডসহ ৩টি লুপ রাউন্ড।',
  '5 min': '৫ মিনিট',
  'Adjust your planned breathing map.': 'পরিকল্পিত শ্বাস-মানচিত্র প্রয়োজনে সংশোধন করুন।',
  'Al-Alaq 96:1-5': 'আল-আলাক ৯৬:১-৫',
  'Al-Qadr 97:1-5': 'আল-কদর ৯৭:১-৫',
  'Aligned shadow': 'সমন্বিত শ্যাডো',
  'Are heavy letters distinct from lighter neighbors?': 'ভারী হরফগুলো কি হালকা পাশের হরফ থেকে স্পষ্টভাবে আলাদা?',
  'Are natural madd sounds kept at consistent count?': 'প্রাকৃতিক মাদ্দ কি ধারাবাহিক মাত্রায় রাখা হচ্ছে?',
  'At least 80% of marked points match replay.': 'চিহ্নিত পয়েন্টের অন্তত ৮০% রি-প্লের সাথে মিলে যায়।',
  'Avoid clipping long vowels to stay aligned.': 'সমন্বয় বজায় রাখতে দীর্ঘ স্বর কেটে ছোট করবেন না।',
  'Breath break in weak positions or word merges.': 'দুর্বল স্থানে শ্বাসভঙ্গ বা শব্দ জোড়া লেগে যাওয়া।',
  'Breath point detection': 'শ্বাস-পয়েন্ট শনাক্তকরণ',
  'Catch pronunciation details before speaking.': 'বলবার আগে উচ্চারণের সূক্ষ্ম দিকগুলো ধরুন।',
  'Clear articulation in command and revelation phrases.': 'নির্দেশনা ও ওহির ফ্রেজে স্পষ্ট উচ্চারণ।',
  'Complete one 3-pass listening loop on a short ayah.': 'একটি ছোট আয়াতে ৩-ধাপের একটি পূর্ণ শ্রবণ লুপ সম্পন্ন করুন।',
  'Complete soft and aligned shadow rounds.': 'সফট ও অ্যালাইন্ড শ্যাডো রাউন্ড সম্পন্ন করুন।',
  'Concise ayah delivery with confident endings.': 'আত্মবিশ্বাসী সমাপ্তিসহ সংক্ষিপ্ত আয়াত উপস্থাপন।',
  'Confidence-ready recitation sample.': 'আত্মবিশ্বাস-প্রস্তুত তিলাওয়াত নমুনা।',
  'Daily listening drill': 'দৈনিক শ্রবণ ড্রিল',
  'Detect and fix two recurring pronunciation mistakes.': 'পুনরাবৃত্ত ২টি উচ্চারণভুল শনাক্ত করে সংশোধন করুন।',
  'Do not rush to catch up after missed syllables.': 'সিলেবল মিস হলে ধরতে গিয়ে তাড়াহুড়ো করবেন না।',
  'Do you pause at safe boundaries only?': 'আপনি কি শুধু নিরাপদ সীমাতেই থামছেন?',
  'Does speed remain stable from start to end?': 'শুরু থেকে শেষ পর্যন্ত গতি কি স্থির থাকে?',
  'Error correction': 'ভুল সংশোধন',
  'Error spotting and correction': 'ভুল শনাক্তকরণ ও সংশোধন',
  'Error-spot routine': 'ভুল-শনাক্ত রুটিন',
  'Fast opening then slowed ending from breath loss.': 'শুরুর অংশ দ্রুত, পরে শ্বাস কমে শেষাংশ ধীর হয়ে যাওয়া।',
  'Final check': 'চূড়ান্ত যাচাই',
  'Focused listening warm-up': 'মনোযোগী শ্রবণ ওয়ার্ম-আপ',
  'Heavy/light confusion': 'ভারী/হালকা ধ্বনি বিভ্রান্তি',
  'Identify two mistakes and apply targeted fixes.': 'দুটি ভুল শনাক্ত করে লক্ষ্যভিত্তিক সংশোধন প্রয়োগ করুন।',
  'Improved second attempt recording.': 'দ্বিতীয় চেষ্টার উন্নত রেকর্ডিং।',
  'Independent recitation with minimal hesitation.': 'ন্যূনতম দ্বিধাসহ স্বতন্ত্র তিলাওয়াত।',
  'Isolate pair words and shadow slowly before full recitation.': 'পূর্ণ তিলাওয়াতের আগে জোড়া-শব্দ আলাদা করে ধীরে শ্যাডো করুন।',
  'Keep transitions smooth instead of pausing between words.': 'শব্দের মাঝে থেমে না গিয়ে রূপান্তর মসৃণ রাখুন।',
  'Keyword listening map': 'মূলশব্দ শ্রবণ মানচিত্র',
  'Lag shadow': 'বিলম্বিত শ্যাডো',
  'Listen again and compare with actual pause points.': 'আবার শুনে বাস্তব বিরতি-পয়েন্টের সাথে তুলনা করুন।',
  'Listen once and guess breath points.': 'একবার শুনে শ্বাস-পয়েন্ট অনুমান করুন।',
  'Long vowels become short on repeated rounds.': 'পুনরাবৃত্ত রাউন্ডে দীর্ঘ স্বর ছোট হয়ে যায়।',
  'Madd length drift': 'মাদ্দের দৈর্ঘ্য বিচ্যুতি',
  'Mark repeated words while listening.': 'শোনার সময় পুনরাবৃত্ত শব্দগুলো চিহ্নিত করুন।',
  'Mark stop points visually and practice planned pauses.': 'থামার স্থান দৃশ্যমানভাবে চিহ্নিত করে পরিকল্পিত বিরতি অনুশীলন করুন।',
  'Match start/end of phrases exactly with reciter.': 'কারির সাথে ফ্রেজের শুরু/শেষ ঠিকমতো মেলান।',
  'No clipped endings and clear command transition.': 'সমাপ্তি কাটা নয় এবং নির্দেশ-রূপান্তর স্পষ্ট।',
  'No mid-word or weak-boundary breath positions.': 'শব্দের মাঝখানে বা দুর্বল সীমায় শ্বাস-বিরতি নয়।',
  'Note where pace slows or emphasis increases.': 'কোথায় গতি ধীর হয় বা জোর বাড়ে তা নোট করুন।',
  'One clean pass at prayer pace.': 'সালাতের গতিতে একবার পরিষ্কার পূর্ণ রাউন্ড।',
  'One list of target sound cues.': 'লক্ষ্য ধ্বনি-সংকেতের একটি তালিকা।',
  'Pass 1: Listen for full ayah rhythm only.': 'পাস ১: শুধু পূর্ণ আয়াতের ছন্দ শুনুন।',
  'Pass 2: Listen for articulation points and clear consonants.': 'পাস ২: উচ্চারণস্থান ও স্পষ্ট ব্যঞ্জনধ্বনি শুনুন।',
  'Pass 3: Listen for madd and stop positions.': 'পাস ৩: মাদ্দ ও থামার স্থান শুনুন।',
  'Recite 3 short passages in one uninterrupted session.': 'একটানা সেশনে ৩টি ছোট অংশ তিলাওয়াত করুন।',
  'Recite half-second behind audio for control and memory support.': 'নিয়ন্ত্রণ ও স্মৃতিসহায়তার জন্য অডিওর অর্ধ সেকেন্ড পরে তিলাওয়াত করুন।',
  'Recite quietly under the audio to match shape and timing.': 'উচ্চারণরূপ ও সময় মিলাতে অডিওর সাথে নিচু স্বরে তিলাওয়াত করুন।',
  'Recite without audio using learned rhythm.': 'শেখা ছন্দ ব্যবহার করে অডিও ছাড়া তিলাওয়াত করুন।',
  'Recognize where to breathe without breaking meaning.': 'অর্থ ভাঙা ছাড়া কোথায় শ্বাস নিতে হবে তা চিনুন।',
  'Record one passage and compare with reference playback.': 'একটি অংশ রেকর্ড করে রেফারেন্স প্লেব্যাকের সাথে তুলনা করুন।',
  'Replay and verify your markings.': 'রি-প্লে করে আপনার চিহ্নগুলো যাচাই করুন।',
  'Retain same rhythm and stops learned from shadow round.': 'শ্যাডো রাউন্ডে শেখা একই ছন্দ ও বিরতি বজায় রাখুন।',
  'Revision and mastery check': 'রিভিশন ও দক্ষতা যাচাই',
  'Rhythm consistency in repeated phrase structure.': 'পুনরাবৃত্ত ফ্রেজ গঠনে ছন্দের ধারাবাহিকতা।',
  'Rhythm inconsistency': 'ছন্দের অসামঞ্জস্য',
  'Run one focused listening loop on selected ayah.': 'নির্বাচিত আয়াতে একটি মনোযোগী শ্রবণ লুপ চালান।',
  'Run two shadow rounds and compare phrase timing.': 'দুটি শ্যাডো রাউন্ড চালিয়ে ফ্রেজের সময়মাত্রা তুলনা করুন।',
  'Saad sounds like seen, qaaf sounds like kaaf.': 'সাদ সীনের মতো শোনা যায়, ক্বাফ কাফের মতো শোনা যায়।',
  'Self-record and compare': 'স্ব-রেকর্ড ও তুলনা',
  'Self-record compare': 'স্ব-রেকর্ড তুলনা',
  'Session planning and pacing': 'সেশন পরিকল্পনা ও গতি নিয়ন্ত্রণ',
  'Shadow consistency check': 'শ্যাডো ধারাবাহিকতা যাচাই',
  'Shadow recitation rounds': 'শ্যাডো তিলাওয়াত রাউন্ড',
  'Shadow training': 'শ্যাডো অনুশীলন',
  'Soft shadow': 'নরম শ্যাডো',
  'Solo recitation': 'একক তিলাওয়াত',
  'Solo transfer': 'এককে রূপান্তর',
  'Stable phrase timing match with audio.': 'অডিওর সাথে ফ্রেজের স্থিতিশীল সময়মিল।',
  'Stable tempo and smooth phrase joins.': 'স্থিতিশীল গতি ও মসৃণ ফ্রেজ-সংযোগ।',
  'Stop audio and recite same ayah independently.': 'অডিও বন্ধ করে একই আয়াত স্বতন্ত্রভাবে তিলাওয়াত করুন।',
  'Stop/restart instability': 'থামা/পুনরারম্ভের অস্থিরতা',
  'Strong qaf and balanced pause points.': 'দৃঢ় ক্বাফ উচ্চারণ ও ভারসাম্যপূর্ণ বিরতি-পয়েন্ট।',
  'Targeted sample practice': 'লক্ষ্যভিত্তিক স্যাম্পল অনুশীলন',
  'Three-pass listening loop': 'তিন-ধাপ শ্রবণ লুপ',
  'Track recurring words and transitions in short ayahs.': 'ছোট আয়াতে পুনরাবৃত্ত শব্দ ও রূপান্তরগুলো অনুসরণ করুন।',
  'Train one ayah per breath with controlled, even tempo.': 'নিয়ন্ত্রিত, সমান গতিতে প্রতি শ্বাসে একটি আয়াত অনুশীলন করুন।',
  'Use finger count for each madd and re-run phrase twice.': 'প্রতিটি মাদ্দ আঙুলে গুনে ফ্রেজ দুইবার পুনরায় অনুশীলন করুন।',
  'Warm-up listening': 'ওয়ার্ম-আপ শ্রবণ',
  'Weekly confidence pass': 'সাপ্তাহিক আত্মবিশ্বাস রাউন্ড',
  'You can describe 2 specific sound details from memory.': 'আপনি স্মৃতি থেকে ২টি নির্দিষ্ট ধ্বনি-তথ্য বর্ণনা করতে পারেন।',

};
