const Map<String, String> readQuranBnContentMap = <String, String>{
  // Home and navigation
  'Read Quran': 'কুরআন পড়ুন',
  'Quran For All': 'কুরআন ফর অল',
  'Search': 'খুঁজুন',
  'Settings': 'সেটিংস',
  'All Surahs': 'সব সূরা',
  'Surah': 'সূরা',
  'total': 'মোট',
  'Continue Reading': 'পড়া চালিয়ে যান',
  'Ayah': 'আয়াত',
  'Bookmarks': 'বুকমার্কসমূহ',
  'Save ayah bookmark': 'আয়াত বুকমার্ক করুন',
  'Remove ayah bookmark': 'আয়াত বুকমার্ক সরান',
  'Mark ayah as last read': 'শেষ পড়া হিসেবে আয়াত চিহ্নিত করুন',
  'Read tafsir': 'তাফসির পড়ুন',
  'Tafsir': 'তাফসির',
  'No tafsir available for this ayah yet.':
      'এই আয়াতের তাফসির এখনও পাওয়া যায়নি।',
  'Save surah bookmark': 'সূরা বুকমার্ক করুন',
  'Remove surah bookmark': 'সূরা বুকমার্ক সরান',

  // Banner and summary
  'Read. Reflect. Remember.': 'পড়ুন। ভাবুন। মনে রাখুন।',
  'Offline Quran with Bangla and English support.':
      'বাংলা ও ইংরেজি সমর্থনসহ অফলাইন কুরআন।',
  'Surahs': 'সূরা',
  'Offline Ready': 'অফলাইনে প্রস্তুত',
  'Search Surah, Ayah, Juz': 'সূরা, আয়াত, পারা খুঁজুন',

  // Search view
  'Search Quran': 'কুরআন অনুসন্ধান',
  'Search Surah, Ayah, or Juz': 'সূরা, আয়াত বা পারা খুঁজুন',
  'Use query formats like 1:1, para 2, or any Bangla/English keyword.':
      '1:1, para 2 বা বাংলা/ইংরেজি কীওয়ার্ড ব্যবহার করুন।',
  'Search failed': 'অনুসন্ধান ব্যর্থ',
  'No results': 'কোনো ফলাফল নেই',
  'Try a shorter keyword or a direct ayah reference.':
      'ছোট কীওয়ার্ড বা সরাসরি আয়াত রেফারেন্স ব্যবহার করুন।',
  'Could not open this result.': 'এই ফলাফল খোলা যায়নি।',
  'Could not open this bookmark.': 'এই বুকমার্ক খোলা যায়নি।',
  'Try: Al-Baqarah, 2:255, para 1, mercy':
      'চেষ্টা করুন: Al-Baqarah, 2:255, para 1, mercy',
  'Searching...': 'অনুসন্ধান চলছে...',
  'Results': 'ফলাফল',
  'Could not load bookmarks': 'বুকমার্ক লোড করা যায়নি',
  'No bookmarks yet': 'এখনও কোনো বুকমার্ক নেই',
  'Save ayah or surah bookmarks to find them quickly later.':
      'পরে দ্রুত খুঁজে পেতে আয়াত বা সূরা বুকমার্ক করে রাখুন।',
  'Saved bookmark': 'সংরক্ষিত বুকমার্ক',

  // Surah details
  'Could not load surah': 'সূরা লোড করা যায়নি',
  'Unable to play this ayah audio right now.':
      'এই মুহূর্তে এই আয়াতের অডিও চালানো যাচ্ছে না।',
  'Unable to play full surah audio right now.':
      'এই মুহূর্তে পূর্ণ সূরার অডিও চালানো যাচ্ছে না।',
  'Play Full Surah': 'পূর্ণ সূরা চালান',
  'Stop Surah Audio': 'সূরার অডিও বন্ধ করুন',
  'Expand card': 'কার্ড প্রসারিত করুন',
  'Shrink card': 'কার্ড সঙ্কুচিত করুন',
  'Reading options': 'পাঠের অপশনসমূহ',
  'Pronunciation and translation visibility':
      'উচ্চারণ ও অনুবাদের প্রদর্শন নিয়ন্ত্রণ',
  'Reading mode': 'পাঠ মোড',
  'Details': 'বিস্তারিত',
  'Regular': 'সাধারণ',
  'Details view': 'বিস্তারিত ভিউ',
  'Regular view': 'সাধারণ ভিউ',
  'Notification permission is required for audio controls.':
      'অডিও কন্ট্রোলের জন্য নোটিফিকেশন অনুমতি প্রয়োজন।',
  'Go to settings': 'সেটিংসে যান',
  'ayahs': 'আয়াত',
  'Meccan': 'মক্কী',
  'Medinan': 'মাদানী',

  // Surah english translation names
  'The Opening': 'উদ্বোধন',
  'The Cow': 'গাভী',
  'The Family of Imran': 'ইমরানের পরিবার',
  'The Women': 'নারীগণ',
  'The Table Spread': 'খাদ্য-সজ্জিত টেবিল',
  'The Cattle': 'গবাদি পশু',
  'The Heights': 'উচ্চ স্থানসমূহ',
  'The Spoils of War': 'যুদ্ধলব্ধ সম্পদ',
  'The Repentance': 'তওবা',
  'Jonah': 'ইউনুস',
  'Hud': 'হুদ',
  'Joseph': 'ইউসুফ',
  'The Thunder': 'বজ্রধ্বনি',
  'Abraham': 'ইবরাহিম',
  'The Rocky Tract': 'শিলাময় ভূমি',
  'The Bee': 'মৌমাছি',
  'The Night Journey': 'রাত্রিযাত্রা',
  'The Cave': 'গুহা',
  'Mary': 'মরিয়ম',
  'Ta-Ha': 'ত্বা-হা',
  'The Prophets': 'নবীগণ',
  'The Pilgrimage': 'হজ',
  'The Believers': 'মুমিনগণ',
  'The Light': 'আলো',
  'The Criterion': 'পার্থক্যকারী',
  'The Poets': 'কবিদের',
  'The Ant': 'পিপীলিকা',
  'The Stories': 'কাহিনিসমূহ',
  'The Spider': 'মাকড়সা',
  'The Romans': 'রোমানরা',
  'Luqman': 'লুকমান',
  'The Prostration': 'সিজদা',
  'The Combined Forces': 'সম্মিলিত বাহিনী',
  'Sheba': 'সাবা',
  'The Originator': 'সৃষ্টির সূচনাকারী',
  'Ya Sin': 'ইয়া-সীন',
  'Those Who Set The Ranks': 'সারিবদ্ধরা',
  'Sad': 'সাদ',
  'The Groups': 'দলসমূহ',
  'The Forgiver': 'ক্ষমাকারী',
  'Explained in Detail': 'বিস্তারিতভাবে বর্ণিত',
  'The Consultation': 'পরামর্শ',
  'The Gold Adornments': 'স্বর্ণ অলংকার',
  'The Smoke': 'ধোঁয়া',
  'The Crouching': 'নতজানু',
  'The Wind-Curved Sandhills': 'বালুকা টিলা',
  'Muhammad': 'মুহাম্মদ',
  'The Victory': 'বিজয়',
  'The Rooms': 'কক্ষসমূহ',
  'Qaf': 'ক্বাফ',
  'The Winnowing Winds': 'বিক্ষেপকারী বাতাস',
  'The Mount': 'তূর পর্বত',
  'The Star': 'নক্ষত্র',
  'The Moon': 'চাঁদ',
  'The Beneficent': 'পরম করুণাময়',
  'The Inevitable': 'নিশ্চিত ঘটনা',
  'The Iron': 'লোহা',
  'The Pleading Woman': 'আবেদনকারী নারী',
  'The Exile': 'নির্বাসন',
  'She That is to be Examined': 'পরীক্ষিত নারী',
  'The Ranks': 'সারি',
  'The Congregation, Friday': 'সমবেতকরণ (জুমা)',
  'The Hypocrites': 'মুনাফিকগণ',
  'Mutual Disillusion': 'মোহমুক্তি',
  'Divorce': 'তালাক',
  'The Prohibition': 'নিষেধাজ্ঞা',
  'The Sovereignty': 'সার্বভৌমত্ব',
  'The Pen': 'কলম',
  'The Reality': 'বাস্তবতা',
  'The Ascending Stairways': 'আরোহনের সোপান',
  'Noah': 'নূহ',
  'The Jinn': 'জিন',
  'The Enshrouded One': 'চাদরে আবৃত ব্যক্তি',
  'The Cloaked One': 'আবৃত ব্যক্তি',
  'The Resurrection': 'পুনরুত্থান',
  'Man': 'মানব',
  'The Emissaries': 'প্রেরিতরা',
  'The Announcement': 'মহাসংবাদ',
  'Those Who Drag Forth': 'যারা টেনে বের করে',
  'He Frowned': 'তিনি ভ্রূকুটি করলেন',
  'The Overthrowing': 'আবর্তন',
  'The Cleaving': 'বিদীর্ণ হওয়া',
  'Defrauding': 'মাপে কম দেওয়া',
  'The Splitting Open': 'বিদীর্ণ',
  'The Constellations': 'নক্ষত্রমণ্ডলী',
  'The Morning Star': 'রাত্রির আগন্তুক',
  'The Most High': 'সর্বোচ্চ',
  'The Overwhelming': 'আচ্ছন্নকারী',
  'The Dawn': 'ফজর',
  'The City': 'নগর',
  'The Sun': 'সূর্য',
  'The Night': 'রাত',
  'The Morning Hours': 'পূর্বাহ্ন',
  'The Relief': 'প্রশস্ততা',
  'The Fig': 'ডুমুর',
  'The Clot': 'রক্তপিণ্ড',
  'The Power, Fate': 'শবে কদর',
  'The Evidence': 'সুস্পষ্ট প্রমাণ',
  'The Earthquake': 'ভূমিকম্প',
  'The Courser': 'অশ্বারোহী',
  'The Calamity': 'মহাবিপর্যয়',
  'Competition': 'প্রাচুর্যের প্রতিযোগিতা',
  'The Declining Day, Epoch': 'সময়',
  'The Traducer': 'পরনিন্দাকারী',
  'The Elephant': 'হাতি',
  'Quraysh': 'কুরাইশ',
  'Small Kindnesses': 'সামান্য সহায়তা',
  'Abundance': 'প্রাচুর্য',
  'The Disbelievers': 'অবিশ্বাসীরা',
  'Divine Support': 'ঐশী সহায়তা',
  'The Palm Fibre': 'খেজুরের তন্তু',
  'Sincerity': 'নিষ্ঠা',
  'The Daybreak': 'প্রভাত',
  'Mankind': 'মানবজাতি',

  // Viewmodel message keys
  'Search failed. Please try again.':
      'অনুসন্ধান ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
  'No surah selected.': 'কোনো সূরা নির্বাচন করা হয়নি।',
  'Unable to load ayahs for this surah.': 'এই সূরার আয়াতগুলো লোড করা যায়নি।',
  'Unable to load bookmarks right now.':
      'এই মুহূর্তে বুকমার্ক লোড করা যাচ্ছে না।',

  // Settings
  'Personalize your recitation and reading experience.':
      'আপনার তিলাওয়াত ও পাঠ অভিজ্ঞতা ব্যক্তিগতকৃত করুন।',
  'Reading Preferences': 'পাঠ পছন্দসমূহ',
  'Show pronunciation': 'উচ্চারণ দেখান',
  'Display transliteration under Arabic ayah.':
      'আরবি আয়াতের নিচে প্রতিলিপি প্রদর্শন করুন।',
  'Show translations': 'অনুবাদ দেখান',
  'Display meaning in your selected language.':
      'নির্বাচিত ভাষায় অর্থ প্রদর্শন করুন।',
  'Language preference': 'ভাষা পছন্দ',
  'Appearance': 'অ্যাপিয়ারেন্স',
  'Theme': 'থিম',
  'System': 'সিস্টেম',
  'Light': 'লাইট',
  'Dark': 'ডার্ক',
  'Offline mode is enabled': 'অফলাইন মোড চালু আছে',
  'Quran text and translations are stored locally after setup. Audio is cached after first play.':
      'সেটআপের পরে কুরআনের লেখা ও অনুবাদ স্থানীয়ভাবে সংরক্ষিত। অডিও প্রথমবার চালানোর পরে ক্যাশ হয়।',
  'Quran text, translations, and tafsir are stored locally after setup. Audio is cached after first play.':
      'সেটআপের পরে কুরআনের লেখা, অনুবাদ ও তাফসির স্থানীয়ভাবে সংরক্ষিত। অডিও প্রথমবার চালানোর পরে ক্যাশ হয়।',
};
